# Exploring the data for Buoy CHII2 for the year 2005 - 2018.

GLERL  
Location: 41.916N 87.572W  

East of Chicago

### Table of contents

Exploring the data:  
[2005](#2005), 
[2006](#2006), 
[2007](#2007),  
[2008](#2008)  
[2009](#2009)  
[2010](#2010)  
[2011](#2011)  
[2012](#2012)  
[2013](#2013)  
[2014](#2014)  
[2015](#2015),
[2016](#2016), 
[2017](#2017), 
[2018](#2018), 
[2019](#2019)

<a id='2005'></a>
### Exploring the data for 2005.

### CHII2
#### Starting Oct 1, 2006, there are daily averages for the following
 - (ATMP) air temperature 
 - (WDIR) Wind Direction 
 - (WSPD) Wind Speed 
 - (GST) "Peak 5 or 8 second gust speed (m/s) measured during the eight-minute or two-minute period. The 5 or 8 second period can be determined by payload, See the Sensor Reporting, Sampling, and Accuracy section." 
 
#### Missing data
 - Some in 2005
 - Some in 2006 (before 10)
 - Nov. 10-12, 2007
 
[Data Dictionary](https://www.ndbc.noaa.gov/measdes.shtml)

In [3]:
import pandas as pd
import time

In [2]:
data_05 = pd.read_csv('../data/buoy_CHII2/chii2h2005.csv')
print(data_05.shape)
data_05.head()

(6804, 18)

,YYYY,MM,DD,hh,mm,WD,WSP,D GST,WVHT,DPD,APD,MWD,BAR,ATMP,WTMP,DEWP,VIS,TIDE
0,2005,2,14,20,0,300,9.3,11.8,99,99,99,999,9999,3.8,999,999,99,99
1,2005,2,14,21,0,290,10.8,12.9,99,99,99,999,9999,4.6,999,999,99,99
2,2005,2,14,22,0,280,11.8,14.4,99,99,99,999,9999,5.1,999,999,99,99
3,2005,2,14,23,0,290,11.8,14.4,99,99,99,999,9999,4.7,999,999,99,99
4,2005,2,15,0,0,280,9.3,11.3,99,99,99,999,9999,4.7,999,999,99,99

In [3]:
data_05.rename(mapper={
    'YYYY': '#YY',
    'WD': 'WDIR',
    'WSP': 'WSPD',
    'D GST': 'GST'
}, axis=1, inplace=True)

In [4]:
data_05.isnull().sum()

#YY     0
MM      0
DD      0
hh      0
mm      0
WDIR    0
WSPD    0
GST     0
WVHT    0
DPD     0
APD     0
MWD     0
BAR     0
ATMP    0
WTMP    0
DEWP    0
VIS     0
TIDE    0
dtype: int64

In [5]:
# there are 28 fields in the 'ATMP' feature that are not reported.
sum(data_05['ATMP'] == 999)

28

In [6]:
data_05[data_05['ATMP'] == 999]

,#YY,MM,DD,hh,mm,WDIR,WSPD,GST,WVHT,DPD,APD,MWD,BAR,ATMP,WTMP,DEWP,VIS,TIDE
483,2005,3,8,11,0,360,8.2,10.3,99,99,99,999,9999,999.0,999,999,99,99
484,2005,3,8,12,0,360,9.8,11.3,99,99,99,999,9999,999.0,999,999,99,99
485,2005,3,8,13,0,340,9.3,10.8,99,99,99,999,9999,999.0,999,999,99,99
486,2005,3,8,14,0,350,8.2,9.3,99,99,99,999,9999,999.0,999,999,99,99
487,2005,3,8,15,0,350,8.2,9.8,99,99,99,999,9999,999.0,999,999,99,99
488,2005,3,8,16,0,360,8.2,9.8,99,99,99,999,9999,999.0,999,999,99,99
489,2005,3,8,17,0,10,9.8,10.8,99,99,99,999,9999,999.0,999,999,99,99
490,2005,3,8,18,0,20,7.7,9.8,99,99,99,999,9999,999.0,999,999,99,99
491,2005,3,8,19,0,30,7.7,9.3,99,99,99,999,9999,999.0,999,999,99,99
492,2005,3,8,20,0,30,7.2,8.8,99,99,99,999,9999,999.0,999,999,99,99
493,2005,3,8,21,0,20,6.7,8.2,99,99,99,999,9999,999.0,999,999,99,99
494,2005,3,8,22,0,20,5.7,6.7,99,99,99,999,9999,999.0,999,999,99,99
495,2005,3,8,23,0,340,5.7,7.7,99,99,99,999,9999,999.0,999,999,99,99
496,2005,3,9,0,0,330,6.2,7.2,99,99,99,999,9999,999.0,999,999,99,99
497,2005,3,9,1,0,340,6.2,7.7,99,99,99,999,9999,999.0,999,999,99,99
498,2005,3,9,2,0,340,4.1,5.1,99,99,99,999,9999,999.0,999,999,99,99
499,2005,3,9,3,0,340,4.1,5.1,99,99,99,999,9999,999.0,999,999,99,99
500,2005,3,9,4,0,340,4.6,6.2,99,99,99,999,9999,999.0,999,999,99,99
501,2005,3,9,5,0,340,5.1,6.7,99,99,99,999,9999,999.0,999,999,99,99
502,2005,3,9,6,0,350,7.2,7.7,99,99,99,999,9999,999.0,999,999,99,99
503,2005,3,9,7,0,360,8.8,10.8,99,99,99,999,9999,999.0,999,999,99,99
504,2005,3,9,8,0,360,8.2,9.3,99,99,99,999,9999,999.0,999,999,99,99
505,2005,3,9,9,0,330,6.7,7.7,99,99,99,999,9999,999.0,999,999,99,99
506,2005,3,9,10,0,340,7.2,8.2,99,99,99,999,9999,999.0,999,999,99,99
507,2005,3,9,11,0,330,6.2,6.7,99,99,99,999,9999,999.0,999,999,99,99
508,2005,3,9,12,0,330,5.7,7.2,99,99,99,999,9999,999.0,999,999,99,99
1096,2005,4,7,3,0,10,6.7,7.2,99,99,99,999,9999,999.0,999,999,99,99
1409,2005,4,20,15,0,20,8.8,10.3,99,99,99,999,9999,999.0,999,999,99,99

In [7]:
data_05.dtypes

#YY       int64
MM        int64
DD        int64
hh        int64
mm        int64
WDIR      int64
WSPD    float64
GST     float64
WVHT      int64
DPD       int64
APD       int64
MWD       int64
BAR       int64
ATMP    float64
WTMP      int64
DEWP      int64
VIS       int64
TIDE      int64
dtype: object

In [8]:
data_05.columns

Index(['#YY', 'MM', 'DD', 'hh', 'mm', 'WDIR', 'WSPD', 'GST', 'WVHT', 'DPD',
       'APD', 'MWD', 'BAR', 'ATMP', 'WTMP', 'DEWP', 'VIS', 'TIDE'],
      dtype='object')

In [9]:
features = ['#YY', 'MM', 'DD', 'hh', 'mm', 'WDIR', 'WSPD', 'GST', 'ATMP', 'DEWP']

In [10]:
data_2005 = data_05[features]

In [11]:
data_2005.head()

    #YY  MM  DD  hh  mm  WDIR  WSPD   GST  ATMP  DEWP
0  2005   2  14  20   0   300   9.3  11.8   3.8   999
1  2005   2  14  21   0   290  10.8  12.9   4.6   999
2  2005   2  14  22   0   280  11.8  14.4   5.1   999
3  2005   2  14  23   0   290  11.8  14.4   4.7   999
4  2005   2  15   0   0   280   9.3  11.3   4.7   999

In [12]:
data_2005.groupby(['#YY', 'MM', 'DD']).mean().drop('hh', axis=1)

             mm        WDIR       WSPD        GST        ATMP   DEWP
#YY  MM DD
2005 2  14  0.0  290.000000  10.925000  13.375000    4.550000  999.0
        15  0.0  168.750000   4.912500   5.808333    3.520833  999.0
        16  0.0  289.583333   7.245833   8.420833   -0.620833  999.0
        17  0.0  305.000000   9.522727  11.295455   -4.413636  999.0
        18  0.0  262.916667   6.329167   7.683333   -7.570833  999.0
        19  0.0  273.333333   7.320833   8.808333   -1.733333  999.0
        20  0.0  175.000000   8.150000   9.333333    0.658333  999.0
        21  0.0  225.000000   5.083333   5.820833    1.416667  999.0
        22  0.0  230.714286   4.964286   5.464286   -0.042857  999.0
        23  0.0  219.583333   3.679167   4.170833   -1.133333  999.0
        24  0.0  134.583333   4.125000   4.508333   -0.395833  999.0
        25  0.0  205.000000   4.758333   5.466667    0.666667  999.0
        26  0.0   70.000000   6.583333   7.404167   -0.929167  999.0
        27  0.0  158.571429   8.142857   9.207143   -0.614286  999.0
        28  0.0  212.083333   6.700000   7.666667    0.237500  999.0
     3  1   0.0  335.416667  10.962500  12.958333   -4.120833  999.0
        2   0.0  293.478261   8.626087  10.052174   -6.378261  999.0
        3   0.0  223.333333   5.070833   5.945833   -3.945833  999.0
        4   0.0  181.250000   3.687500   4.079167    0.487500  999.0
        5   0.0  129.166667   4.650000   5.079167    1.458333  999.0
        6   0.0  262.272727  10.604545  12.931818    7.513636  999.0
        7   0.0  219.583333  12.791667  15.512500    8.766667  999.0
        8   0.0  199.230769   7.876923   9.430769  999.000000  999.0
        9   0.0  266.363636   6.500000   7.690909  588.345455  999.0
        10  0.0  258.333333   7.766667   9.050000   -2.579167  999.0
        11  0.0  314.782609   9.721739  11.508696   -0.200000  999.0
        12  0.0  270.588235   9.758824  11.870588   -2.500000  999.0
        13  0.0  191.875000   5.025000   6.112500   -3.806250  999.0
        14  0.0  148.750000   2.937500   3.529167   -0.900000  999.0
        15  0.0  264.166667   4.920833   5.766667   -0.716667  999.0
...         ...         ...        ...        ...         ...    ...
     12 2   0.0  313.043478   9.139130  11.191304   -6.352174  999.0
        3   0.0  198.333333   4.608333   5.983333   -4.220833  999.0
        4   0.0  263.750000   6.891667   8.050000   -2.929167  999.0
        5   0.0  298.695652   6.778261   8.108696   -8.973913  999.0
        6   0.0  294.166667   5.316667   6.583333  -10.112500  999.0
        7   0.0  297.083333   5.520833   6.850000  -12.162500  999.0
        8   0.0  202.083333   5.791667   7.083333   -6.666667  999.0
        9   0.0  259.583333   7.495833   8.962500   -4.654167  999.0
        10  0.0  223.913043  12.086957  14.282609   -7.260870  999.0
        11  0.0  312.083333   7.862500   9.420833   -1.966667  999.0
        12  0.0  323.750000   4.929167   5.729167   -3.516667  999.0
        13  0.0  260.416667   4.775000   5.833333   -3.941667  999.0
        14  0.0  174.166667  11.291667  13.516667   -1.854167  999.0
        15  0.0  226.521739   6.982609   8.130435    0.730435  999.0
        16  0.0  269.166667  10.512500  13.408333   -3.900000  999.0
        17  0.0  271.538462   8.553846  10.661538   -6.423077  999.0
        18  0.0  295.416667   6.950000   8.458333   -9.587500  999.0
        19  0.0  290.833333   7.833333   9.470833  -12.812500  999.0
        20  0.0  281.250000   8.125000   9.725000   -9.295833  999.0
        21  0.0  285.416667   5.533333   6.708333   -7.625000  999.0
        22  0.0  236.250000   8.637500  10.325000   -3.754167  999.0
        23  0.0  232.500000   9.862500  11.975000    3.954167  999.0
        24  0.0  195.833333   5.354167   5.966667    3.633333  999.0
        25  0.0  179.583333  10.175000  11.304167    1.441667  999.0
        26  0.0  332.083333   7.441667   8.608333    1.579167  999.0
        27  0.0  199.565217   7.286957   8.239130    1.395652  999.0
        28  0.0   80.416667   7.191667   7.895833    2.708333  999.0
        29  0.0  295.652174  10.408696  11.660870    1.265217  999.0
        30  0.0   90.000000   2.780000   3.090000    0.610000  999.0
        31  0.0  292.500000   9.000000  10.175000    2.375000  999.0

[305 rows x 6 columns]

<a id='2006'></a>
### Exploring the data for 2006.

In [13]:
data_06 = pd.read_csv('../data/buoy_CHII2/chii2h2006.csv')
print(data_06.shape)
data_06.head()

(2182, 18)

,YYYY,MM,DD,hh,mm,WD,WSP,D GST,WVHT,DPD,APD,MWD,BAR,ATMP,WTMP,DEWP,VIS,TIDE
0,2006,3,1,0,0,280,12.4,14.4,99,99,99,999,9999,9.8,999,999,99,99
1,2006,3,30,14,0,190,4.6,5.7,99,99,99,999,9999,5.6,999,999,99,99
2,2006,3,30,16,0,180,6.7,7.2,99,99,99,999,9999,8.1,999,999,99,99
3,2006,3,30,17,0,180,8.8,9.3,99,99,99,999,9999,10.3,999,999,99,99
4,2006,3,30,18,0,190,8.8,10.3,99,99,99,999,9999,11.9,999,999,99,99

In [14]:
data_06.rename(mapper={
    'YYYY': '#YY',
    'WD': 'WDIR',
    'WSP': 'WSPD',
    'D GST': 'GST'
}, axis=1, inplace=True)

In [15]:
data_06.tail()

,#YY,MM,DD,hh,mm,WDIR,WSPD,GST,WVHT,DPD,APD,MWD,BAR,ATMP,WTMP,DEWP,VIS,TIDE
2177,2006,12,31,17,0,140,10.3,12.9,99,99,99,999,9999,5.5,999,999,99,99
2178,2006,12,31,18,0,150,9.8,12.4,99,99,99,999,9999,5.7,999,999,99,99
2179,2006,12,31,20,0,150,8.8,10.3,99,99,99,999,9999,7.5,999,999,99,99
2180,2006,12,31,21,0,160,7.2,8.8,99,99,99,999,9999,9.4,999,999,99,99
2181,2006,12,31,22,0,230,10.3,13.4,99,99,99,999,9999,13.6,999,999,99,99

In [16]:
data_2006 = data_06[features]
data_2006.head()

    #YY  MM  DD  hh  mm  WDIR  WSPD   GST  ATMP  DEWP
0  2006   3   1   0   0   280  12.4  14.4   9.8   999
1  2006   3  30  14   0   190   4.6   5.7   5.6   999
2  2006   3  30  16   0   180   6.7   7.2   8.1   999
3  2006   3  30  17   0   180   8.8   9.3  10.3   999
4  2006   3  30  18   0   190   8.8  10.3  11.9   999

In [17]:
pd.options.display.max_rows = 500

In [18]:
data_2006.groupby(['#YY', 'MM', 'DD']).mean().drop(['hh', 'mm'], axis=1).tail(100)

                  WDIR       WSPD        GST       ATMP   DEWP
#YY  MM DD
2006 7  12  310.434783   5.556522   6.295652  19.695652  999.0
        13  185.416667   2.991667   3.575000  20.612500  999.0
        14  130.869565   4.695652   5.521739  23.043478  999.0
        15  201.111111   4.233333   4.911111  26.150000  999.0
        16  220.000000   5.568182   6.568182  29.077273  999.0
        17  199.285714   8.714286  10.678571  29.528571  999.0
        18  124.285714   9.942857  11.842857  27.428571  999.0
        19   76.000000   6.720000   7.633333  23.040000  999.0
     10 1   193.000000   4.190000   4.905000  15.790000  999.0
        2   142.222222   9.811111  11.705556  19.527778  999.0
        3   145.714286   7.019048   8.214286  18.676190  999.0
        4   261.176471  12.352941  14.652941  18.200000  999.0
        5    37.000000  10.845000  12.875000  13.100000  999.0
        6    60.000000   6.276190   7.895238  12.152381  999.0
        7   138.421053   6.315789   7.610526  13.142105  999.0
        8   186.470588   7.176471   8.258824  16.458824  999.0
        9   250.476190   5.076190   5.819048  16.771429  999.0
        10   99.473684   8.447368   9.794737  12.800000  999.0
        11  179.411765   6.847059   8.964706  12.270588  999.0
        12  261.111111  11.677778  15.194444   2.333333  999.0
        13  242.777778  12.711111  17.144444   4.422222  999.0
        14  265.000000   9.231250  11.712500   7.037500  999.0
        15  239.411765   6.305882   7.517647   7.635294  999.0
        16  170.000000   8.833333  10.594444  11.405556  999.0
        17  202.777778   9.111111  10.861111  11.727778  999.0
        18  215.263158   4.878947   5.747368  14.147368  999.0
        19  312.380952   6.642857   8.161905   6.319048  999.0
        20  254.285714   5.878571   7.478571   6.621429  999.0
        21  179.047619   7.128571   8.385714  11.171429  999.0
        22  261.052632   9.157895  11.389474   5.931579  999.0
        23  277.894737   8.173684  10.226316   3.300000  999.0
        24  289.047619   6.571429   8.104762   3.371429  999.0
        25  237.692308   3.176923   3.800000   6.400000  999.0
        26  124.117647   9.223529  10.617647   7.952941  999.0
        27   59.411765   8.000000   9.411765   6.911765  999.0
        28  277.894737  11.847368  14.600000   7.378947  999.0
        29  256.250000   7.000000   8.531250   7.431250  999.0
        30  181.764706  10.088235  11.382353  12.794118  999.0
        31  245.000000  11.920000  14.855000  11.545000  999.0
     11 1   291.333333   6.806667   8.580000   2.866667  999.0
        2   277.333333   9.060000  11.293333   1.373333  999.0
        3   269.375000   6.231250   7.818750   0.556250  999.0
        4   188.666667   8.893333  10.746667   5.500000  999.0
        5   181.428571   6.280952   7.180952   8.104762  999.0
        6   175.555556   6.066667   6.772222   9.522222  999.0
        7   121.666667   3.433333   3.872222  10.122222  999.0
        8   194.666667   4.466667   5.073333   9.773333  999.0
        9   156.363636   7.818182   9.209091  13.454545  999.0
        10   43.125000   8.756250  10.112500   8.512500  999.0
        11  329.000000  15.260000  17.735000   4.490000  999.0
        12  180.000000   5.453846   7.115385   4.423077  999.0
        13  186.428571   8.978571  10.550000   3.314286  999.0
        14  212.222222   4.311111   5.033333   5.455556  999.0
        15   73.125000   8.850000  10.262500   6.956250  999.0
        16  140.526316  16.889474  20.131579   5.994737  999.0
        17  280.000000   7.400000   8.984615   3.176923  999.0
        18  303.333333   4.566667   5.488889   4.288889  999.0
        19  342.352941  10.982353  12.911765   3.835294  999.0
        20  316.250000   6.450000   7.587500   2.025000  999.0
        21  190.769231   7.384615   8.400000   4.184615  999.0
        22  173.571429   7.235714   8.164286   5.492857  999.0
        23  162.105263   5.647368   6.205263   6.589474  999.0
        24  159.285714   7.392857   8.235714   7.664286  999.0
        25  183.846154   6.261538   6.815385  11.115385  999.0
        26  178.000000   5.240000   6.070000  12.710000  999.0
        27  181.875000   6.462500   7.462500  13.493750  999.0
        28  172.777778   8.527778   9.583333  12.855556  999.0
        29  191.333333   9.873333  11.646667  14.433333  999.0
        30  326.666667  10.261111  12.022222   2.094444  999.0
     12 1    92.000000  14.966667  17.993333   1.380000  999.0
        2   234.375000   8.556250  10.812500  -3.531250  999.0
        3   269.375000   9.462500  11.931250  -7.693750  999.0
        4   230.555556   9.988889  12.955556  -7.827778  999.0
        5   245.882353   9.229412  11.447059  -7.023529  999.0
        6   231.578947  11.868421  14.542105   0.984211  999.0
        7   307.058824  11.247059  14.070588  -7.923529  999.0
        8   253.333333   8.677778  11.077778  -9.344444  999.0
        9   197.500000  12.312500  15.006250  -2.625000  999.0
        10  199.444444  11.933333  14.638889   3.255556  999.0
        11  184.444444   8.405556   9.833333   5.088889  999.0
        12  166.000000   7.960000   9.026667   6.886667  999.0
        13  227.777778   8.733333  11.711111   4.172222  999.0
        14  202.777778  10.061111  12.133333   7.394444  999.0
        15  257.894737   9.110526  11.673684   6.621053  999.0
        16  186.470588   8.200000   9.288235   4.517647  999.0
        17  267.000000   6.465000   7.390000   8.850000  999.0
        18  258.000000   4.955000   5.660000   2.725000  999.0
        19  264.210526   3.694737   4.378947   1.221053  999.0
        20  194.705882   5.447059   6.347059   1.964706  999.0
        21   94.285714   6.764286   7.507143   4.121429  999.0
        22  149.375000   7.656250   8.943750   7.837500  999.0
        23  248.000000  10.815000  14.380000   3.975000  999.0
        24  241.428571   5.880952   7.128571   2.176190  999.0
        25  241.578947   6.126316   7.026316   2.915789  999.0
        26  318.750000  10.143750  11.843750   1.100000  999.0
        27  228.888889   6.266667   7.638889   0.711111  999.0
        28  156.000000   6.286667   7.173333   3.646667  999.0
        29  115.333333   4.926667   5.460000   5.026667  999.0
        30  166.250000   2.656250   3.068750   5.875000  999.0
        31  121.111111   8.472222   9.933333   6.577778  999.0

<a id='2007'></a>
### Exploring the data for 2007.
 - 10/10-12/2007 are missing

In [19]:
data_07 = pd.read_csv('../data/buoy_CHII2/chii2h2007.csv')
print(data_07.shape)
data_07.head()

(6697, 18)

,#YY,MM,DD,hh,mm,WDI,R WSP,D GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,TIDE
0,#yr,mo,dy,hr,mn,deg,T m/s,m/s,m,sec,sec,deg,T hPa,degC,degC,degC,nmi,ft
1,2007,1,1,0,0,210,11.8,17,99,99,99,999,9999,11.8,999,999,99,99
2,2007,1,1,1,0,210,9.3,11.3,99,99,99,999,9999,10.6,999,999,99,99
3,2007,1,1,2,0,220,11.3,14.4,99,99,99,999,9999,10.2,999,999,99,99
4,2007,1,1,4,0,200,13.4,15.4,99,99,99,999,9999,8,999,999,99,99

In [20]:
sum(data_07['ATMP'] == 999)

0

In [21]:
sum(data_07['WDI'] == 999)

0

In [22]:
sum(data_07['R WSP'] == 999)

0

In [23]:
data_07.head()

,#YY,MM,DD,hh,mm,WDI,R WSP,D GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,TIDE
0,#yr,mo,dy,hr,mn,deg,T m/s,m/s,m,sec,sec,deg,T hPa,degC,degC,degC,nmi,ft
1,2007,1,1,0,0,210,11.8,17,99,99,99,999,9999,11.8,999,999,99,99
2,2007,1,1,1,0,210,9.3,11.3,99,99,99,999,9999,10.6,999,999,99,99
3,2007,1,1,2,0,220,11.3,14.4,99,99,99,999,9999,10.2,999,999,99,99
4,2007,1,1,4,0,200,13.4,15.4,99,99,99,999,9999,8,999,999,99,99

In [24]:
data_07.rename(mapper={
    'WDI': 'WDIR',
    'R WSP': 'WSPD',
    'D GST': 'GST'
}, axis=1, inplace=True)

In [25]:
data_07.head()

,#YY,MM,DD,hh,mm,WDIR,WSPD,GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,TIDE
0,#yr,mo,dy,hr,mn,deg,T m/s,m/s,m,sec,sec,deg,T hPa,degC,degC,degC,nmi,ft
1,2007,1,1,0,0,210,11.8,17,99,99,99,999,9999,11.8,999,999,99,99
2,2007,1,1,1,0,210,9.3,11.3,99,99,99,999,9999,10.6,999,999,99,99
3,2007,1,1,2,0,220,11.3,14.4,99,99,99,999,9999,10.2,999,999,99,99
4,2007,1,1,4,0,200,13.4,15.4,99,99,99,999,9999,8,999,999,99,99

In [26]:
data_2007 = data_07[features]

In [27]:
data_2007.drop(index=0, inplace=True)
print(data_2007.shape)
data_2007.head()

(6696, 10)

/Users/blakewallace/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:3940: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

    #YY MM DD hh mm WDIR  WSPD   GST  ATMP DEWP
1  2007  1  1  0  0  210  11.8    17  11.8  999
2  2007  1  1  1  0  210   9.3  11.3  10.6  999
3  2007  1  1  2  0  220  11.3  14.4  10.2  999
4  2007  1  1  4  0  200  13.4  15.4     8  999
5  2007  1  1  5  0  220  10.8    16   7.5  999

In [28]:
data_2007.dtypes

#YY     object
MM      object
DD      object
hh      object
mm      object
WDIR    object
WSPD    object
GST     object
ATMP    object
DEWP    object
dtype: object

In [29]:
data_2007.shape

(6696, 10)

In [30]:
data_2007[['WSPD', 'GST', 'ATMP']] = data_2007[['WSPD', 'GST', 'ATMP']].astype('float')

/Users/blakewallace/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:3391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[k1] = value[k2]

In [31]:
data_2007.shape

(6696, 10)

In [32]:
data_2007.dtypes

#YY      object
MM       object
DD       object
hh       object
mm       object
WDIR     object
WSPD    float64
GST     float64
ATMP    float64
DEWP     object
dtype: object

In [33]:
data_2007[['#YY', 'MM', 'DD', 'hh', 'mm', 'WDIR']] = data_2007[['#YY', 'MM', 'DD', 'hh', 'mm', 'WDIR']].astype('int')

In [34]:
data_2007.shape

(6696, 10)

In [35]:
data_2007.dtypes

#YY       int64
MM        int64
DD        int64
hh        int64
mm        int64
WDIR      int64
WSPD    float64
GST     float64
ATMP    float64
DEWP     object
dtype: object

In [36]:
data_2007[data_2007['MM'] == 12]

       #YY  MM  DD  hh  mm  WDIR  WSPD   GST   ATMP DEWP
6064  2007  12   1   0   0   260   7.7   9.8   -3.0  999
6065  2007  12   1   1   0   280   7.7   9.8   -3.7  999
6066  2007  12   1   2   0   280   6.7   7.7   -4.0  999
6067  2007  12   1   3   0   290   6.2   7.7   -4.2  999
6068  2007  12   1   4   0   290   5.7   7.2   -4.4  999
6069  2007  12   1   6   0   320   5.1   6.2   -4.7  999
6070  2007  12   1   8   0   320   3.1   4.1   -4.5  999
6071  2007  12   1   9   0   270   3.6   4.6   -4.3  999
6072  2007  12   1  10   0   300   2.1   3.1   -4.2  999
6073  2007  12   1  11   0   320   2.1   3.1   -4.0  999
6074  2007  12   1  12   0   300   1.5   2.1   -3.6  999
6075  2007  12   1  13   0   200   3.1   3.6   -3.0  999
6076  2007  12   1  14   0   120   7.7   9.8   -1.5  999
6077  2007  12   1  16   0   130   9.8  11.3   -1.4  999
6078  2007  12   1  17   0   150   8.8  12.4   -1.2  999
6079  2007  12   1  18   0   130  10.8  12.9   -1.1  999
6080  2007  12   1  19   0   140  11.3  14.4   -1.7  999
6081  2007  12   1  20   0   140  11.8  14.4   -2.6  999
6082  2007  12   1  21   0   130  14.4  17.0   -2.2  999
6083  2007  12   1  22   0   130  11.3  12.4   -1.8  999
6084  2007  12   1  23   0   120   4.1   4.6   -1.2  999
6085  2007  12   2   0   0   130   1.5   1.5   -0.9  999
6086  2007  12   2   2   0   150   1.0   1.5   -0.1  999
6087  2007  12   2   3   0   160   0.5   1.0    0.3  999
6088  2007  12   2   4   0   170   0.5   1.0    0.4  999
6089  2007  12   2   5   0   170   8.8  16.0    0.8  999
6090  2007  12   2   6   0   170  11.8  13.9    1.8  999
6091  2007  12   2   7   0   180  14.4  16.5    2.4  999
6092  2007  12   2   8   0   180  14.4  16.0    3.4  999
6093  2007  12   2   9   0   180  14.4  16.0    5.0  999
6094  2007  12   2  10   0   200  12.9  15.4    6.2  999
6095  2007  12   2  12   0   190  11.8  13.4    7.2  999
6096  2007  12   2  13   0   190  10.8  12.4    7.4  999
6097  2007  12   2  14   0   200  10.8  12.9    8.1  999
6098  2007  12   2  15   0   200   9.3  10.3    8.4  999
6099  2007  12   2  16   0   200   8.2   9.8    7.9  999
6100  2007  12   2  17   0   190   7.7   8.8    8.8  999
6101  2007  12   2  18   0   210   6.2   7.2    9.4  999
6102  2007  12   2  19   0   320   5.1   6.2    7.4  999
6103  2007  12   2  20   0   320   6.2   7.2    5.1  999
6104  2007  12   2  22   0   300   9.8  11.3    3.4  999
6105  2007  12   2  23   0   280  10.3  13.9    3.1  999
6106  2007  12   3   1   0   280  13.9  16.0    1.5  999
6107  2007  12   3   2   0   280  13.4  17.0    0.3  999
6108  2007  12   3   3   0   280  12.9  17.5   -0.1  999
6109  2007  12   3   4   0   280  12.4  14.9   -0.5  999
6110  2007  12   3   6   0   280  13.9  18.0   -2.0  999
6111  2007  12   3   7   0   280  15.4  18.5   -2.4  999
6112  2007  12   3   8   0   280  12.9  16.0   -3.1  999
6113  2007  12   3   9   0   280  13.4  16.0   -3.6  999
6114  2007  12   3  11   0   300  12.4  15.4   -3.9  999
6115  2007  12   3  12   0   280  11.3  13.9   -4.5  999
6116  2007  12   3  14   0   290   9.3  11.3   -5.5  999
6117  2007  12   3  15   0   270  12.9  15.4   -6.3  999
6118  2007  12   3  16   0   290   9.3  11.3   -5.3  999
6119  2007  12   3  17   0   270   9.8  11.3   -4.4  999
6120  2007  12   3  18   0   270   7.7  10.3   -3.4  999
6121  2007  12   3  19   0   280   7.7   9.3   -2.2  999
6122  2007  12   3  20   0   270  10.3  12.4   -1.4  999
6123  2007  12   3  21   0   270  10.8  12.9   -1.9  999
6124  2007  12   3  22   0   270   9.3  10.3   -2.0  999
6125  2007  12   3  23   0   270   7.7   9.3   -1.6  999
6126  2007  12   4   0   0   280   7.7   9.3   -1.9  999
6127  2007  12   4   1   0   270   6.7   7.7   -1.8  999
6128  2007  12   4   2   0   270   4.6   5.1   -1.8  999
6129  2007  12   4   3   0   260   6.7   7.7   -2.0  999
6130  2007  12   4   4   0   270   7.2   8.2   -2.2  999
6131  2007  12   4   5   0   270   7.7   8.8   -2.1  999
6132  2007  12   4   6   0   280   7.7   9.3   -2.4  999
6133  2007  12   4  10   0   340   6.2   8.2   -2.3  999
6134  2007  12   4  11   0   340   5.1   5.7   -1.8  999
6135  2007  12   4  12   0   360   4.6   5.1   -1.0  999
6136  2007  12   4  13   0   300   4.6   5.1   -1.9  999
6137  2007  12   4  14   0   360   5.7   6.7   -0.5  999
6138  2007  12   4  15   0    20   5.1   6.2   -0.5  999
6139  2007  12   4  16   0    10   4.6   5.7   -0.5  999
6140  2007  12   4  17   0    10   3.6   4.6   -0.1  999
6141  2007  12   4  18   0   340   2.6   3.6   -0.1  999
6142  2007  12   4  19   0   340   4.1   5.1   -0.9  999
6143  2007  12   4  20   0   340   4.1   4.6   -0.3  999
6144  2007  12   4  21   0    50   2.1   3.1    0.1  999
6145  2007  12   4  23   0    30   2.6   3.1    0.1  999
6146  2007  12   5   0   0    50   2.6   3.1   -0.9  999
6147  2007  12   5   1   0    90   2.6   2.6   -1.4  999
6148  2007  12   5   2   0    90   5.1   6.2   -1.2  999
6149  2007  12   5   4   0   200   5.7   6.7   -1.4  999
6150  2007  12   5   5   0   190   6.7   7.2   -1.3  999
6151  2007  12   5   6   0   170   4.6   5.1   -1.4  999
6152  2007  12   5   8   0   130   5.1   6.2   -1.4  999
6153  2007  12   5   9   0   100  10.3  11.3   -1.1  999
6154  2007  12   5  11   0    60  13.4  16.5   -1.4  999
6155  2007  12   5  13   0    40  13.4  16.5   -1.4  999
6156  2007  12   5  14   0    30  12.9  15.4   -1.5  999
6157  2007  12   5  15   0    30  12.9  14.9   -1.4  999
6158  2007  12   5  16   0    20  14.4  18.0   -1.6  999
6159  2007  12   5  17   0    20  14.4  17.0   -2.0  999
6160  2007  12   5  18   0    10  11.8  14.4   -1.9  999
6161  2007  12   5  19   0   320  11.3  13.9   -3.4  999
6162  2007  12   5  22   0   330  11.8  13.9   -3.0  999
6163  2007  12   5  23   0   320   9.8  11.8   -4.0  999
6164  2007  12   6   3   0   300   7.7   9.3   -6.8  999
6165  2007  12   6   4   0   310   8.2  10.3   -7.2  999
6166  2007  12   6   5   0   320   6.7   7.7   -7.0  999
6167  2007  12   6   6   0   310   6.2   7.2   -7.3  999
6168  2007  12   6   7   0   300   4.6   6.2   -7.5  999
6169  2007  12   6   8   0   300   4.6   6.2   -7.5  999
6170  2007  12   6   9   0   280   4.1   5.1   -7.7  999
6171  2007  12   6  10   0   260   3.6   4.1   -7.9  999
6172  2007  12   6  11   0   250   2.6   3.1   -7.4  999
6173  2007  12   6  12   0   260   4.6   5.7   -8.5  999
6174  2007  12   6  13   0   260   5.1   6.2   -8.5  999
6175  2007  12   6  14   0   260   4.6   6.2   -8.2  999
6176  2007  12   6  15   0   250   3.6   5.7   -7.6  999
6177  2007  12   6  16   0   200   5.7   7.7   -7.2  999
6178  2007  12   6  17   0   200   7.2   8.8   -7.0  999
6179  2007  12   6  18   0   200   7.7   9.8   -6.1  999
6180  2007  12   6  19   0   200   6.2   8.2   -5.8  999
6181  2007  12   6  20   0   200   5.1   6.7   -5.1  999
6182  2007  12   6  21   0   200   5.7   7.2   -4.8  999
6183  2007  12   6  22   0   200   6.2   7.7   -4.8  999
6184  2007  12   6  23   0   190   7.7   8.8   -4.7  999
6185  2007  12   7   0   0   180   8.2   9.8   -4.7  999
6186  2007  12   7   1   0   180   8.2   9.3   -4.4  999
6187  2007  12   7   2   0   180  10.3  12.4   -3.9  999
6188  2007  12   7   4   0   200   7.2   8.8   -4.4  999
6189  2007  12   7   5   0   190   7.2   8.8   -4.1  999
6190  2007  12   7   6   0   180   8.8  10.3   -3.5  999
6191  2007  12   7   9   0   200   7.2   8.2   -2.9  999
6192  2007  12   7  10   0   210   6.7   9.3   -2.6  999
6193  2007  12   7  11   0   220   5.7   7.2   -2.3  999
6194  2007  12   7  12   0   240   5.1   6.7   -2.2  999
6195  2007  12   7  13   0   240   6.2   8.2   -2.1  999
6196  2007  12   7  14   0   240   6.2   8.2   -2.0  999
6197  2007  12   7  15   0   250   6.2   8.2   -2.0  999
6198  2007  12   7  16   0   260   6.2   7.7   -1.9  999
6199  2007  12   7  17   0   250   6.2   7.2   -1.6  999
6200  2007  12   7  19   0   260   7.7   8.8   -1.4  999
6201  2007  12   7  20   0   240   5.1   6.7   -1.2  999
6202  2007  12   7  22   0   240   7.7   9.3   -1.2  999
6203  2007  12   7  23   0   260   6.7   8.2   -1.2  999
6204  2007  12   8   0   0   240   6.2   8.2   -1.1  999
6205  2007  12   8   1   0   240   5.7   6.7   -1.2  999
6206  2007  12   8   2   0   260   6.2   7.2   -1.2  999
6207  2007  12   8   3   0   260   7.2   8.8   -1.3  999
6208  2007  12   8   4   0   260   7.2   8.8   -1.3  999
6209  2007  12   8   5   0   280   7.2   8.8   -1.6  999
6210  2007  12   8   6   0   280   7.2   7.7   -2.4  999
6211  2007  12   8   7   0   270   6.2   6.7   -2.7  999
6212  2007  12   8  10   0   320   7.7   9.3   -5.1  999
6213  2007  12   8  11   0   330   8.2  10.8   -5.7  999
6214  2007  12   8  12   0   320   6.7   8.8   -6.0  999
6215  2007  12   8  13   0   320   7.2   8.2   -7.1  999
6216  2007  12   8  14   0   310   6.7   8.2   -7.5  999
6217  2007  12   8  15   0   320   6.2   7.2   -6.7  999
6218  2007  12   8  16   0   330   6.2   7.2   -6.0  999
6219  2007  12   8  17   0   330   6.7   7.7   -6.2  999
6220  2007  12   8  18   0   340   8.8   9.8   -5.8  999
6221  2007  12   8  20   0   350   8.2   9.8   -3.9  999
6222  2007  12   8  22   0    10   5.7   6.7   -2.3  999
6223  2007  12   8  23   0   360   5.7   6.7   -2.0  999
6224  2007  12   9   1   0    20   6.2   7.7   -1.5  999
6225  2007  12   9   2   0    30   5.1   6.2   -0.9  999
6226  2007  12   9   3   0    30   5.7   7.2   -0.4  999
6227  2007  12   9   4   0    30   6.2   7.7   -0.5  999
6228  2007  12   9   6   0    80   2.1   2.1   -1.0  999
6229  2007  12   9   7   0    80   1.0   1.5   -1.0  999
6230  2007  12   9   9   0    60   1.0   1.0   -0.8  999
6231  2007  12   9  10   0    60   1.5   1.5   -1.0  999
6232  2007  12   9  12   0    60   1.5   1.5   -0.7  999
6233  2007  12   9  13   0    50   1.5   2.1   -0.6  999
6234  2007  12   9  14   0    50   1.5   2.1   -0.4  999
6235  2007  12   9  16   0    60   2.1   2.1   -0.7  999
6236  2007  12   9  17   0    50   2.1   2.1   -0.8  999
6237  2007  12   9  18   0    70   1.0   1.5   -0.6  999
6238  2007  12   9  19   0    60   1.0   1.5   -0.4  999
6239  2007  12   9  20   0    50   1.5   2.1   -0.3  999
6240  2007  12   9  21   0    20   2.1   2.6   -0.4  999
6241  2007  12   9  22   0    30   2.1   2.6   -0.5  999
6242  2007  12   9  23   0    40   1.5   2.1    0.0  999
6243  2007  12  10   0   0    20   1.5   2.1    0.4  999
6244  2007  12  10   2   0    30   1.5   2.1    0.7  999
6245  2007  12  10   4   0    30   5.1   6.2    0.7  999
6246  2007  12  10   6   0    30   5.1   6.2    0.7  999
6247  2007  12  10   7   0   320   8.8   9.3   -1.3  999
6248  2007  12  10   9   0   330   8.8   9.3   -1.4  999
6249  2007  12  10  10   0   330   8.8   9.8   -1.9  999
6250  2007  12  10  11   0   320   8.2   9.8   -1.9  999
6251  2007  12  10  12   0   320   7.2   8.2   -1.4  999
6252  2007  12  10  13   0   330   8.2   9.3   -1.1  999
6253  2007  12  10  14   0   330   8.2   9.3   -1.7  999
6254  2007  12  10  15   0   310   5.1   6.2   -1.7  999
6255  2007  12  10  16   0   330   5.1   5.7   -1.3  999
6256  2007  12  10  17   0   220   1.5   2.1   -1.0  999
6257  2007  12  10  18   0   290   2.1   3.1   -0.6  999
6258  2007  12  10  19   0   210   2.1   2.6   -0.1  999
6259  2007  12  10  20   0   200   2.1   2.1    0.1  999
6260  2007  12  10  22   0   150   2.1   2.6    0.5  999
6261  2007  12  11   0   0   150   2.6   3.1    0.8  999
6262  2007  12  11   1   0   160   3.6   4.6    0.8  999
6263  2007  12  11   2   0   170   5.1   6.2    0.8  999
6264  2007  12  11   4   0   170   6.2   7.2   -0.5  999
6265  2007  12  11   5   0   160   7.7   9.8   -1.3  999
6266  2007  12  11   6   0   170   7.2   8.8   -1.6  999
6267  2007  12  11   7   0   190   6.2   7.7   -1.4  999
6268  2007  12  11  10   0   150   1.5   2.1   -1.1  999
6269  2007  12  11  11   0   120   2.6   3.6   -0.7  999
6270  2007  12  11  13   0   190   1.5   2.1   -0.2  999
6271  2007  12  11  14   0   150   1.0   2.1   -0.1  999
6272  2007  12  11  15   0   140   4.1   5.1    0.8  999
6273  2007  12  11  16   0   180   1.5   1.5    0.7  999
6274  2007  12  11  17   0   220   2.6   2.6    0.6  999
6275  2007  12  11  18   0   330   1.0   1.5    0.6  999
6276  2007  12  11  19   0   310   3.1   3.1    0.9  999
6277  2007  12  11  20   0   320   4.1   4.6    0.7  999
6278  2007  12  11  21   0   320   4.6   5.1    0.7  999
6279  2007  12  11  22   0   320   4.6   5.7    0.7  999
6280  2007  12  11  23   0   320   5.1   6.2    0.6  999
6281  2007  12  12   1   0   330   6.2   7.2    0.5  999
6282  2007  12  12   2   0   330   9.8  10.8    0.3  999
6283  2007  12  12   3   0   320   8.8   9.3    0.1  999
6284  2007  12  12   4   0   310   6.7   7.7    0.1  999
6285  2007  12  12   5   0   320   7.7   8.8   -0.3  999
6286  2007  12  12   6   0   330   8.2   9.8   -0.5  999
6287  2007  12  12   7   0   340  10.3  11.8   -0.8  999
6288  2007  12  12   8   0   330   8.8   9.8   -1.1  999
6289  2007  12  12   9   0   330   8.8  11.3   -1.2  999
6290  2007  12  12  10   0   330   8.2   9.3   -1.5  999
6291  2007  12  12  11   0   330   9.8  11.3   -1.7  999
6292  2007  12  12  13   0   330   8.8  10.3   -2.7  999
6293  2007  12  12  14   0   320   8.8  10.8   -2.7  999
6294  2007  12  12  15   0   330   8.2   9.8   -2.6  999
6295  2007  12  12  16   0   330   8.2   9.3   -2.4  999
6296  2007  12  12  18   0   330   5.1   5.7   -1.0  999
6297  2007  12  12  20   0    80   4.6   6.2    1.2  999
6298  2007  12  12  22   0    70   4.1   5.1    1.5  999
6299  2007  12  12  23   0    70   4.1   5.1    1.5  999
6300  2007  12  13   0   0    80   5.7   6.7    1.7  999
6301  2007  12  13   1   0   100   6.2   7.7    2.0  999
6302  2007  12  13   2   0   120   7.2   7.7    2.3  999
6303  2007  12  13   3   0   120   7.7   9.3    2.0  999
6304  2007  12  13   5   0   130   8.8  10.3    1.7  999
6305  2007  12  13   6   0   140   8.2  10.3    1.7  999
6306  2007  12  13   7   0   160   6.2   7.7    1.5  999
6307  2007  12  13   8   0   170   5.7   6.7    1.4  999
6308  2007  12  13   9   0   180   3.6   4.6    1.4  999
6309  2007  12  13  10   0   200   4.6   5.7    0.8  999
6310  2007  12  13  11   0   200   3.1   3.1    0.6  999
6311  2007  12  13  12   0   260   2.6   3.1    0.7  999
6312  2007  12  13  13   0   250   6.2   7.2    0.7  999
6313  2007  12  13  14   0   240   4.6   6.2    0.6  999
...    ...  ..  ..  ..  ..   ...   ...   ...    ...  ...
6447  2007  12  20   0   0   200   4.6   5.1    0.1  999
6448  2007  12  20   2   0   210   3.6   4.6   -0.8  999
6449  2007  12  20   3   0   180   5.1   5.1   -1.4  999
6450  2007  12  20   4   0   170   4.6   5.7   -1.6  999
6451  2007  12  20   5   0   180   5.7   6.7   -1.6  999
6452  2007  12  20   6   0   170   5.7   6.7   -2.2  999
6453  2007  12  20   7   0   170   6.7   7.2   -2.4  999
6454  2007  12  20   8   0   180   6.2   6.7   -2.6  999
6455  2007  12  20   9   0   160   5.7   7.7   -2.0  999
6456  2007  12  20  10   0   160   6.2   8.2   -1.6  999
6457  2007  12  20  11   0   150   6.2   7.7   -1.5  999
6458  2007  12  20  12   0   140   7.2   8.8   -1.1  999
6459  2007  12  20  13   0   150   8.8  10.3   -1.0  999
6460  2007  12  20  14   0   140   7.7  10.3   -1.0  999
6461  2007  12  20  15   0   150   6.7   9.3    0.2  999
6462  2007  12  20  16   0   150   5.7   7.7   -0.1  999
6463  2007  12  20  17   0   140   5.7   6.7    0.6  999
6464  2007  12  20  18   0   110   6.7   7.7    0.9  999
6465  2007  12  20  20   0   120   8.8   9.8    1.8  999
6466  2007  12  20  22   0   110   8.8  10.3    2.5  999
6467  2007  12  20  23   0   120   7.2   8.2    2.7  999
6468  2007  12  21   0   0   110   9.3  10.8    2.6  999
6469  2007  12  21   1   0   130   9.3  10.8    2.4  999
6470  2007  12  21   3   0   120  10.3  11.8    2.3  999
6471  2007  12  21   4   0   130  10.3  12.4    2.1  999
6472  2007  12  21   5   0   130   9.8  10.8    2.1  999
6473  2007  12  21   6   0   140   6.7   8.2    1.5  999
6474  2007  12  21   7   0   140   5.1   6.2    1.1  999
6475  2007  12  21   8   0   110   5.7   6.2    1.5  999
6476  2007  12  21   9   0   130   5.7   6.2    1.4  999
6477  2007  12  21  10   0   120   5.7   6.2    1.5  999
6478  2007  12  21  11   0   140   2.6   3.1    1.1  999
6479  2007  12  21  12   0   110   4.1   4.6    1.4  999
6480  2007  12  21  13   0   130   5.7   6.7    2.2  999
6481  2007  12  21  15   0   150   4.1   5.1    1.8  999
6482  2007  12  21  16   0   140   5.7   6.7    2.1  999
6483  2007  12  21  17   0   140   5.7   7.2    2.1  999
6484  2007  12  21  18   0   150   4.6   5.1    1.9  999
6485  2007  12  21  19   0   150   3.1   4.1    2.3  999
6486  2007  12  21  20   0   120   5.7   6.2    2.2  999
6487  2007  12  21  21   0   120   5.1   5.7    2.4  999
6488  2007  12  21  22   0   130   5.1   5.7    2.5  999
6489  2007  12  21  23   0   140   5.7   6.2    2.6  999
6490  2007  12  22   0   0   130   5.7   6.2    2.3  999
6491  2007  12  22   1   0   130   6.2   7.2    2.1  999
6492  2007  12  22   2   0   130   7.2   8.2    1.9  999
6493  2007  12  22   3   0   140   5.7   7.2    1.7  999
6494  2007  12  22   4   0   150   6.2   8.2    1.7  999
6495  2007  12  22   5   0   150   6.2   7.7    1.7  999
6496  2007  12  22   6   0   140   5.1   6.7    1.9  999
6497  2007  12  22   7   0   140   4.6   6.2    2.2  999
6498  2007  12  22   8   0   140   4.6   5.7    2.5  999
6499  2007  12  22   9   0   160   2.6   3.6    2.1  999
6500  2007  12  22  10   0   160   4.6   5.1    2.6  999
6501  2007  12  22  11   0   150   3.6   4.6    2.9  999
6502  2007  12  22  12   0   140   3.1   3.1    3.4  999
6503  2007  12  22  13   0   140   5.7   6.2    3.9  999
6504  2007  12  22  14   0   180   4.1   5.7    3.1  999
6505  2007  12  22  15   0   170   9.8  10.8    4.8  999
6506  2007  12  22  16   0   170  10.3  11.3    5.3  999
6507  2007  12  22  17   0   170   9.3  10.3    5.4  999
6508  2007  12  22  18   0   160  10.8  11.3    5.8  999
6509  2007  12  22  20   0   160   8.2   9.8    6.8  999
6510  2007  12  22  21   0   160   9.3   9.8    7.4  999
6511  2007  12  22  22   0   150   7.7   8.8    6.5  999
6512  2007  12  22  23   0   160   9.8  10.8    6.3  999
6513  2007  12  23   0   0   160   9.3  10.8    7.2  999
6514  2007  12  23   1   0   160  11.3  13.4    6.8  999
6515  2007  12  23   2   0   160   9.3  10.3    6.3  999
6516  2007  12  23   3   0   150   9.8  11.3    6.3  999
6517  2007  12  23   4   0   130  10.3  10.8    6.8  999
6518  2007  12  23   5   0   130   7.7   8.8    5.9  999
6519  2007  12  23   6   0   130   9.3  10.8    6.2  999
6520  2007  12  23   7   0   150  11.8  14.4    6.9  999
6521  2007  12  23   8   0   160  13.4  15.4    7.4  999
6522  2007  12  23   9   0   170  24.7  99.0    8.8  999
6523  2007  12  23  10   0   210  24.2  29.3    3.0  999
6524  2007  12  23  11   0   230  21.6  27.3   -2.9  999
6525  2007  12  23  12   0   230  18.5  23.7   -6.2  999
6526  2007  12  23  13   0   230  16.0  22.7   -7.8  999
6527  2007  12  23  14   0   230  17.0  22.7   -8.1  999
6528  2007  12  23  16   0   230  14.4  20.1   -9.0  999
6529  2007  12  23  17   0   240  17.0  25.2   -9.5  999
6530  2007  12  23  18   0   220  16.5  23.7   -9.3  999
6531  2007  12  23  19   0   240  16.0  23.7   -9.3  999
6532  2007  12  23  20   0   230  18.5  24.2   -9.5  999
6533  2007  12  23  21   0   230  15.4  23.7   -8.7  999
6534  2007  12  23  22   0   240  17.0  23.7   -8.2  999
6535  2007  12  23  23   0   220  19.6  27.3   -8.1  999
6536  2007  12  24   0   0   220  18.5  28.3   -7.7  999
6537  2007  12  24   1   0   220  16.0  21.6   -7.2  999
6538  2007  12  24   2   0   240  15.4  22.1   -6.9  999
6539  2007  12  24   3   0   240  15.4  20.1   -6.2  999
6540  2007  12  24   4   0   240  14.9  19.6   -6.2  999
6541  2007  12  24   5   0   240  16.0  21.6   -6.0  999
6542  2007  12  24   6   0   250  16.5  22.7   -6.1  999
6543  2007  12  24   7   0   250  16.0  19.6   -6.0  999
6544  2007  12  24   8   0   240  12.9  16.5   -5.6  999

In [37]:
data_07 = data_2007.groupby(['#YY', 'MM', 'DD']).mean().drop(['hh', 'mm'], axis=1)

In [38]:
data_07.head()

                  WDIR       WSPD        GST      ATMP
#YY  MM DD
2007 1  1   258.333333   9.950000  12.933333  5.316667
        2   254.000000   5.715000   6.585000  2.430000
        3   198.823529  10.717647  12.935294  3.541176
        4   194.117647  12.870588  15.458824  5.852941
        5   222.500000   7.385000   8.775000  8.410000

In [39]:
data_07.shape

(362, 4)

In [40]:
# It is strange that there are only 362 rows in the grouped data above.  

data_2007['MM'] #['DD' == 26]

1        1
2        1
3        1
4        1
5        1
6        1
7        1
8        1
9        1
10       1
11       1
12       1
13       1
14       1
15       1
16       1
17       1
18       1
19       1
20       1
21       1
22       1
23       1
24       1
25       1
26       1
27       1
28       1
29       1
30       1
31       1
32       1
33       1
34       1
35       1
36       1
37       1
38       1
39       1
40       1
41       1
42       1
43       1
44       1
45       1
46       1
47       1
48       1
49       1
50       1
51       1
52       1
53       1
54       1
55       1
56       1
57       1
58       1
59       1
60       1
61       1
62       1
63       1
64       1
65       1
66       1
67       1
68       1
69       1
70       1
71       1
72       1
73       1
74       1
75       1
76       1
77       1
78       1
79       1
80       1
81       1
82       1
83       1
84       1
85       1
86       1
87       1
88       1
89       1
90       1
91       1
92       1
93       1
94       1
95       1
96       1
97       1
98       1
99       1
100      1
101      1
102      1
103      1
104      1
105      1
106      1
107      1
108      1
109      1
110      1
111      1
112      1
113      1
114      1
115      1
116      1
117      1
118      1
119      1
120      1
121      1
122      1
123      1
124      1
125      1
126      1
127      1
128      1
129      1
130      1
131      1
132      1
133      1
134      1
135      1
136      1
137      1
138      1
139      1
140      1
141      1
142      1
143      1
144      1
145      1
146      1
147      1
148      1
149      1
150      1
151      1
152      1
153      1
154      1
155      1
156      1
157      1
158      1
159      1
160      1
161      1
162      1
163      1
164      1
165      1
166      1
167      1
168      1
169      1
170      1
171      1
172      1
173      1
174      1
175      1
176      1
177      1
178      1
179      1
180      1
181      1
182      1
183      1
184      1
185      1
186      1
187      1
188      1
189      1
190      1
191      1
192      1
193      1
194      1
195      1
196      1
197      1
198      1
199      1
200      1
201      1
202      1
203      1
204      1
205      1
206      1
207      1
208      1
209      1
210      1
211      1
212      1
213      1
214      1
215      1
216      1
217      1
218      1
219      1
220      1
221      1
222      1
223      1
224      1
225      1
226      1
227      1
228      1
229      1
230      1
231      1
232      1
233      1
234      1
235      1
236      1
237      1
238      1
239      1
240      1
241      1
242      1
243      1
244      1
245      1
246      1
247      1
248      1
249      1
250      1
        ..
6447    12
6448    12
6449    12
6450    12
6451    12
6452    12
6453    12
6454    12
6455    12
6456    12
6457    12
6458    12
6459    12
6460    12
6461    12
6462    12
6463    12
6464    12
6465    12
6466    12
6467    12
6468    12
6469    12
6470    12
6471    12
6472    12
6473    12
6474    12
6475    12
6476    12
6477    12
6478    12
6479    12
6480    12
6481    12
6482    12
6483    12
6484    12
6485    12
6486    12
6487    12
6488    12
6489    12
6490    12
6491    12
6492    12
6493    12
6494    12
6495    12
6496    12
6497    12
6498    12
6499    12
6500    12
6501    12
6502    12
6503    12
6504    12
6505    12
6506    12
6507    12
6508    12
6509    12
6510    12
6511    12
6512    12
6513    12
6514    12
6515    12
6516    12
6517    12
6518    12
6519    12
6520    12
6521    12
6522    12
6523    12
6524    12
6525    12
6526    12
6527    12
6528    12
6529    12
6530    12
6531    12
6532    12
6533    12
6534    12
6535    12
6536    12
6537    12
6538    12
6539    12
6540    12
6541    12
6542    12
6543    12
6544    12
6545    12
6546    12
6547    12
6548    12
6549    12
6550    12
6551    12
6552    12
6553    12
6554    12
6555    12
6556    12
6557    12
6558    12
6559    12
6560    12
6561    12
6562    12
6563    12
6564    12
6565    12
6566    12
6567    12
6568    12
6569    12
6570    12
6571    12
6572    12
6573    12
6574    12
6575    12
6576    12
6577    12
6578    12
6579    12
6580    12
6581    12
6582    12
6583    12
6584    12
6585    12
6586    12
6587    12
6588    12
6589    12
6590    12
6591    12
6592    12
6593    12
6594    12
6595    12
6596    12
6597    12
6598    12
6599    12
6600    12
6601    12
6602    12
6603    12
6604    12
6605    12
6606    12
6607    12
6608    12
6609    12
6610    12
6611    12
6612    12
6613    12
6614    12
6615    12
6616    12
6617    12
6618    12
6619    12
6620    12
6621    12
6622    12
6623    12
6624    12
6625    12
6626    12
6627    12
6628    12
6629    12
6630    12
6631    12
6632    12
6633    12
6634    12
6635    12
6636    12
6637    12
6638    12
6639    12
6640    12
6641    12
6642    12
6643    12
6644    12
6645    12
6646    12
6647    12
6648    12
6649    12
6650    12
6651    12
6652    12
6653    12
6654    12
6655    12
6656    12
6657    12
6658    12
6659    12
6660    12
6661    12
6662    12
6663    12
6664    12
6665    12
6666    12
6667    12
6668    12
6669    12
6670    12
6671    12
6672    12
6673    12
6674    12
6675    12
6676    12
6677    12
6678    12
6679    12
6680    12
6681    12
6682    12
6683    12
6684    12
6685    12
6686    12
6687    12
6688    12
6689    12
6690    12
6691    12
6692    12
6693    12
6694    12
6695    12
6696    12
Name: MM, Length: 6696, dtype: int64

In [41]:
data_2007['DD'].value_counts(ascending=True)

31    116
29    196
10    198
12    202
11    203
9     207
4     207
30    211
15    213
13    213
8     213
28    214
6     217
26    218
27    220
2     221
16    222
5     223
17    224
25    224
14    225
22    225
24    226
20    230
18    231
7     231
3     232
19    232
1     232
23    233
21    237
Name: DD, dtype: int64

In [42]:
# this shows that the there are three days missing in November.
for i in range(1, 13):
    print(i, len(data_2007[data_2007['MM'] == i]['DD'].value_counts()))

1 31
2 28
3 31
4 30
5 31
6 30
7 31
8 31
9 30
10 31
11 27
12 31

In [43]:
nov_2007 = data_2007[data_2007['MM'] == 11.0]

In [44]:
# showing that days 10-12 in November are not represented.  We might try and populate this information with
# other data.
for i in range(1, 31):
    print(i, len(nov_2007[nov_2007['DD'] == i]))

1 24
2 20
3 22
4 20
5 20
6 20
7 20
8 17
9 5
10 0
11 0
12 0
13 7
14 21
15 14
16 22
17 21
18 21
19 23
20 22
21 22
22 20
23 22
24 21
25 22
26 22
27 17
28 22
29 21
30 22

In [45]:
data_2007.dtypes

#YY       int64
MM        int64
DD        int64
hh        int64
mm        int64
WDIR      int64
WSPD    float64
GST     float64
ATMP    float64
DEWP     object
dtype: object

In [46]:
data_2007.head()

    #YY  MM  DD  hh  mm  WDIR  WSPD   GST  ATMP DEWP
1  2007   1   1   0   0   210  11.8  17.0  11.8  999
2  2007   1   1   1   0   210   9.3  11.3  10.6  999
3  2007   1   1   2   0   220  11.3  14.4  10.2  999
4  2007   1   1   4   0   200  13.4  15.4   8.0  999
5  2007   1   1   5   0   220  10.8  16.0   7.5  999

<a id='2008'></a>
### Exploring the data for 2008.

In [47]:
data_08 = pd.read_csv('../data/buoy_CHII2/chii2h2008.csv')
print(data_08.shape)
data_08.head()

(5138, 18)

,#YY,MM,DD,hh,mm,WDI,R WSP,D GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,TIDE
0,#yr,mo,dy,hr,mn,deg,T m/s,m/s,m,sec,sec,deg,hPa,degC,degC,degC,nmi,ft
1,2008,1,1,0,0,140,4.1,5.1,99,99,99,999,9999,-0.3,999,999,99,99
2,2008,1,1,1,0,100,3.1,3.6,99,99,99,999,9999,-0.4,999,999,99,99
3,2008,1,1,2,0,50,4.1,4.6,99,99,99,999,9999,-0.4,999,999,99,99
4,2008,1,1,3,0,340,4.6,5.1,99,99,99,999,9999,-0.4,999,999,99,99

In [48]:
data_08.rename(mapper={
    'WDI': 'WDIR',
    'R WSP': 'WSPD',
    'D GST': 'GST'
}, axis=1, inplace=True)
data_08.head()

,#YY,MM,DD,hh,mm,WDIR,WSPD,GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,TIDE
0,#yr,mo,dy,hr,mn,deg,T m/s,m/s,m,sec,sec,deg,hPa,degC,degC,degC,nmi,ft
1,2008,1,1,0,0,140,4.1,5.1,99,99,99,999,9999,-0.3,999,999,99,99
2,2008,1,1,1,0,100,3.1,3.6,99,99,99,999,9999,-0.4,999,999,99,99
3,2008,1,1,2,0,50,4.1,4.6,99,99,99,999,9999,-0.4,999,999,99,99
4,2008,1,1,3,0,340,4.6,5.1,99,99,99,999,9999,-0.4,999,999,99,99

In [49]:
data_08.dtypes

#YY     object
MM      object
DD      object
hh      object
mm      object
WDIR    object
WSPD    object
GST     object
WVHT    object
DPD     object
APD     object
MWD     object
PRES    object
ATMP    object
WTMP    object
DEWP    object
VIS     object
TIDE    object
dtype: object

In [50]:
data_08 = data_08.drop(index=0)

In [51]:
data_08.head(100)

,#YY,MM,DD,hh,mm,WDIR,WSPD,GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,TIDE
1,2008,1,1,0,0,140,4.1,5.1,99,99,99,999,9999,-0.3,999,999,99,99
2,2008,1,1,1,0,100,3.1,3.6,99,99,99,999,9999,-0.4,999,999,99,99
3,2008,1,1,2,0,50,4.1,4.6,99,99,99,999,9999,-0.4,999,999,99,99
4,2008,1,1,3,0,340,4.6,5.1,99,99,99,999,9999,-0.4,999,999,99,99
5,2008,1,1,4,0,310,6.7,7.7,99,99,99,999,9999,-0.4,999,999,99,99
6,2008,1,1,5,0,330,13.9,16.5,99,99,99,999,9999,-0.9,999,999,99,99
7,2008,1,1,10,0,300,11.8,15.4,99,99,99,999,9999,-4.9,999,999,99,99
8,2008,1,1,11,0,300,11.3,14.4,99,99,99,999,9999,-4.9,999,999,99,99
9,2008,1,1,12,0,290,10.3,12.4,99,99,99,999,9999,-4.8,999,999,99,99
10,2008,1,1,14,0,280,10.8,12.9,99,99,99,999,9999,-5.7,999,999,99,99
11,2008,1,1,15,0,280,10.3,11.8,99,99,99,999,9999,-5.6,999,999,99,99
12,2008,1,1,16,0,280,9.3,12.4,99,99,99,999,9999,-5.8,999,999,99,99
13,2008,1,1,17,0,290,8.8,10.3,99,99,99,999,9999,-5.7,999,999,99,99
14,2008,1,1,18,0,290,8.8,11.3,99,99,99,999,9999,-5.7,999,999,99,99
15,2008,1,1,19,0,290,9.8,11.8,99,99,99,999,9999,-5.5,999,999,99,99
16,2008,1,1,20,0,300,10.3,12.4,99,99,99,999,9999,-5.7,999,999,99,99
17,2008,1,1,21,0,300,11.3,13.4,99,99,99,999,9999,-6.1,999,999,99,99
18,2008,1,1,22,0,290,12.4,13.9,99,99,99,999,9999,-6.8,999,999,99,99
19,2008,1,1,23,0,300,10.3,11.3,99,99,99,999,9999,-7.5,999,999,99,99
20,2008,1,2,0,0,290,10.3,12.9,99,99,99,999,9999,-8.4,999,999,99,99
21,2008,1,2,1,0,290,11.3,13.9,99,99,99,999,9999,-8.6,999,999,99,99
22,2008,1,2,2,0,290,11.3,14.9,99,99,99,999,9999,-9.5,999,999,99,99
23,2008,1,2,3,0,290,11.8,15.4,99,99,99,999,9999,-10.5,999,999,99,99
24,2008,1,2,4,0,300,11.3,14.4,99,99,99,999,9999,-11.4,999,999,99,99
25,2008,1,2,7,0,300,11.3,13.4,99,99,99,999,9999,-13.7,999,999,99,99
26,2008,1,2,8,0,290,10.8,12.9,99,99,99,999,9999,-14,999,999,99,99
27,2008,1,2,9,0,300,9.3,11.8,99,99,99,999,9999,-14.1,999,999,99,99
28,2008,1,2,11,0,280,8.8,11.3,99,99,99,999,9999,-14.3,999,999,99,99
29,2008,1,2,12,0,290,8.2,10.3,99,99,99,999,9999,-14.1,999,999,99,99
30,2008,1,2,13,0,290,8.2,10.3,99,99,99,999,9999,-13.9,999,999,99,99
31,2008,1,2,14,0,280,8.2,9.8,99,99,99,999,9999,-13.9,999,999,99,99
32,2008,1,2,16,0,280,9.8,12.4,99,99,99,999,9999,-11.6,999,999,99,99
33,2008,1,2,17,0,290,7.7,9.8,99,99,99,999,9999,-10,999,999,99,99
34,2008,1,2,18,0,290,7.7,9.3,99,99,99,999,9999,-8.3,999,999,99,99
35,2008,1,2,19,0,300,8.2,9.8,99,99,99,999,9999,-7.2,999,999,99,99
36,2008,1,2,20,0,300,7.2,8.8,99,99,99,999,9999,-6.6,999,999,99,99
37,2008,1,2,21,0,310,6.7,8.2,99,99,99,999,9999,-6,999,999,99,99
38,2008,1,2,23,0,280,7.7,9.3,99,99,99,999,9999,-6.5,999,999,99,99
39,2008,1,3,1,0,290,8.8,10.8,99,99,99,999,9999,-8.2,999,999,99,99
40,2008,1,3,2,0,280,8.2,9.3,99,99,99,999,9999,-8.7,999,999,99,99
41,2008,1,3,3,0,280,8.2,9.8,99,99,99,999,9999,-9.7,999,999,99,99
42,2008,1,3,5,0,280,6.7,8.2,99,99,99,999,9999,-10.5,999,999,99,99
43,2008,1,3,7,0,280,4.1,5.7,99,99,99,999,9999,-11.1,999,999,99,99
44,2008,1,3,10,0,270,4.6,5.7,99,99,99,999,9999,-12.1,999,999,99,99
45,2008,1,3,11,0,270,3.1,4.6,99,99,99,999,9999,-12,999,999,99,99
46,2008,1,3,13,0,200,5.7,6.7,99,99,99,999,9999,-11.9,999,999,99,99
47,2008,1,3,14,0,200,7.2,8.2,99,99,99,999,9999,-11.7,999,999,99,99
48,2008,1,3,15,0,200,9.8,11.3,99,99,99,999,9999,-12.4,999,999,99,99
49,2008,1,3,16,0,190,8.8,10.3,99,99,99,999,9999,-11.5,999,999,99,99
50,2008,1,3,18,0,200,8.8,10.3,99,99,99,999,9999,-9.2,999,999,99,99
51,2008,1,3,19,0,200,9.3,11.3,99,99,99,999,9999,-8.3,999,999,99,99
52,2008,1,3,20,0,200,10.8,12.9,99,99,99,999,9999,-7.7,999,999,99,99
53,2008,1,3,21,0,190,13.4,16.5,99,99,99,999,9999,-7.3,999,999,99,99
54,2008,1,3,22,0,190,13.9,15.4,99,99,99,999,9999,-7.4,999,999,99,99
55,2008,1,3,23,0,180,14.4,16.5,99,99,99,999,9999,-7.2,999,999,99,99
56,2008,1,4,1,0,190,15.4,18,99,99,99,999,9999,-5.9,999,999,99,99
57,2008,1,4,2,0,190,17,19.6,99,99,99,999,9999,-5.2,999,999,99,99
58,2008,1,4,3,0,190,14.4,17.5,99,99,99,999,9999,-5,999,999,99,99
59,2008,1,4,4,0,190,14.4,18,99,99,99,999,9999,-4.7,999,999,99,99
60,2008,1,4,5,0,190,14.9,19.6,99,99,99,999,9999,-4.5,999,999,99,99
61,2008,1,4,6,0,190,12.9,15.4,99,99,99,999,9999,-4.4,999,999,99,99
62,2008,1,4,9,0,190,11.8,14.4,99,99,99,999,9999,-4.4,999,999,99,99
63,2008,1,4,10,0,190,10.3,12.4,99,99,99,999,9999,-4.2,999,999,99,99
64,2008,1,4,12,0,190,11.8,14.4,99,99,99,999,9999,-3,999,999,99,99
65,2008,1,4,13,0,190,11.3,13.4,99,99,99,999,9999,-3.2,999,999,99,99
66,2008,1,4,14,0,190,13.4,15.4,99,99,99,999,9999,-3.1,999,999,99,99
67,2008,1,4,15,0,190,13.4,16.5,99,99,99,999,9999,-3.4,999,999,99,99
68,2008,1,4,16,0,200,14.9,17.5,99,99,99,999,9999,-3.1,999,999,99,99
69,2008,1,4,17,0,200,11.3,13.9,99,99,99,999,9999,-2.7,999,999,99,99
70,2008,1,4,18,0,190,11.3,13.4,99,99,99,999,9999,-2.1,999,999,99,99
71,2008,1,4,19,0,190,10.3,12.4,99,99,99,999,9999,-1.5,999,999,99,99
72,2008,1,4,20,0,200,11.3,14.4,99,99,99,999,9999,-0.9,999,999,99,99
73,2008,1,4,21,0,190,11.3,12.9,99,99,99,999,9999,-0.3,999,999,99,99
74,2008,1,4,22,0,180,9.8,11.3,99,99,99,999,9999,0.3,999,999,99,99
75,2008,1,4,23,0,180,8.8,10.3,99,99,99,999,9999,0.3,999,999,99,99
76,2008,1,5,1,0,180,10.3,12.9,99,99,99,999,9999,1.4,999,999,99,99
77,2008,1,5,4,0,190,13.9,16,99,99,99,999,9999,2,999,999,99,99
78,2008,1,5,6,0,190,13.9,17,99,99,99,999,9999,2,999,999,99,99
79,2008,1,5,9,0,190,10.8,12.9,99,99,99,999,9999,2.6,999,999,99,99
80,2008,1,5,12,0,190,12.4,13.9,99,99,99,999,9999,2.5,999,999,99,99
81,2008,1,5,13,0,190,11.8,13.9,99,99,99,999,9999,2.9,999,999,99,99
82,2008,1,5,14,0,190,12.9,15.4,99,99,99,999,9999,3.1,999,999,99,99
83,2008,1,5,15,0,190,10.3,12.9,99,99,99,999,9999,3.5,999,999,99,99
84,2008,1,5,16,0,190,11.3,14.9,99,99,99,999,9999,3.9,999,999,99,99
85,2008,1,5,19,0,190,9.8,11.3,99,99,99,999,9999,5,999,999,99,99
86,2008,1,5,20,0,190,10.3,11.8,99,99,99,999,9999,5.4,999,999,99,99
87,2008,1,5,21,0,190,11.3,12.4,99,99,99,999,9999,5.5,999,999,99,99
88,2008,1,5,22,0,190,10.8,12.9,99,99,99,999,9999,5.8,999,999,99,99
89,2008,1,5,23,0,190,10.8,13.4,99,99,99,999,9999,6,999,999,99,99
90,2008,1,6,1,0,190,11.3,12.9,99,99,99,999,9999,6.3,999,999,99,99
91,2008,1,6,2,0,190,10.8,11.8,99,99,99,999,9999,6,999,999,99,99
92,2008,1,6,3,0,180,10.3,11.8,99,99,99,999,9999,6,999,999,99,99
93,2008,1,6,4,0,190,10.3,11.8,99,99,99,999,9999,6,999,999,99,99
94,2008,1,6,5,0,190,11.3,13.4,99,99,99,999,9999,6.1,999,999,99,99
95,2008,1,6,6,0,190,8.8,10.3,99,99,99,999,9999,5.8,999,999,99,99
96,2008,1,6,7,0,180,8.8,9.3,99,99,99,999,9999,5.8,999,999,99,99
97,2008,1,6,8,0,180,7.7,8.8,99,99,99,999,9999,5.8,999,999,99,99
98,2008,1,6,9,0,160,8.2,8.8,99,99,99,999,9999,5.5,999,999,99,99
99,2008,1,6,10,0,170,9.3,9.8,99,99,99,999,9999,6.2,999,999,99,99
100,2008,1,6,12,0,170,9.3,9.8,99,99,99,999,9999,7.1,999,999,99,99

In [52]:
data_08 = data_08[features]
data_08[['WSPD', 'GST', 'ATMP']] = data_08[['WSPD', 'GST', 'ATMP']].astype('float')
data_08[['#YY', 'MM', 'DD', 'hh', 'mm', 'WDIR']] = data_08[['#YY', 'MM', 'DD', 'hh', 'mm', 'WDIR']].astype('int')
data_2008 = data_08[features]
print(data_2008.shape)
data_2008.head()

(5137, 10)

    #YY  MM  DD  hh  mm  WDIR  WSPD  GST  ATMP DEWP
1  2008   1   1   0   0   140   4.1  5.1  -0.3  999
2  2008   1   1   1   0   100   3.1  3.6  -0.4  999
3  2008   1   1   2   0    50   4.1  4.6  -0.4  999
4  2008   1   1   3   0   340   4.6  5.1  -0.4  999
5  2008   1   1   4   0   310   6.7  7.7  -0.4  999

In [53]:
data_08.groupby(['#YY', 'MM', 'DD']).mean().drop(['hh', 'mm'], axis=1)

                  WDIR       WSPD        GST        ATMP
#YY  MM DD
2008 1  1   266.315789   9.052632  10.857895   -4.078947
        2   291.578947   9.252632  11.521053  -10.663158
        3   229.411765   8.576471  10.205882   -9.817647
        4   190.500000  12.500000  15.035000   -3.050000
        5   189.285714  11.471429  13.685714    3.685714
        6   180.952381  10.033333  11.376190    8.238095
        7   201.500000  11.840000  13.775000   14.710000
        8   172.666667  10.546667  12.266667   10.613333
        9   254.500000   7.815000   9.745000    2.135000
        10  117.777778   5.883333   6.616667    2.633333
        11  219.000000   7.270000   8.830000    1.900000
        12  197.619048   6.385714   7.852381    0.376190
        13  213.684211   6.905263   8.231579    1.073684
        14  272.173913   9.969565  12.008696   -3.308696
        15  271.666667   8.383333  10.133333   -7.233333
        16  178.421053   9.921053  11.647368   -2.084211
        17  185.000000   9.005556  10.733333    0.127778
        18  227.222222  10.355556  13.416667   -8.572222
        19  275.909091   9.681818  12.045455  -14.654545
        20  272.307692   9.384615  11.623077  -18.500000
     6  1   150.833333   3.200000   4.029167   96.745833
        2   143.636364   5.136364   5.550000   18.763636
        3   110.000000   6.458333   7.508333   14.533333
        4   340.833333   5.150000   5.766667   12.037500
        5   224.583333   8.241667   9.816667   19.137500
        6   187.083333  14.129167  17.195833   25.591667
        7   189.130435  10.582609  12.443478   23.426087
        8   167.826087   8.978261  10.560870  108.000000
        9   189.166667   8.333333  10.512500  307.041667
        10  231.304348   6.326087   8.117391   20.100000
        11  184.666667   6.353333   7.680000   23.593333
        12  147.391304   8.691304   9.900000   21.886957
        13  202.916667  10.679167  13.212500   23.279167
        14  243.333333   6.845833   8.345833   23.229167
        15  219.545455   8.031818  10.054545   22.645455
        16  220.833333   5.895833   6.816667   19.279167
        17  250.000000   5.020833   6.308333   16.595833
        18  206.250000   5.270833   6.166667   16.720833
        19  120.416667   3.320833   3.745833   16.450000
        20  195.000000   5.879167   6.654167   21.291667
        21  252.083333   6.429167   7.695833   21.925000
        22  193.750000   4.183333   4.937500   20.116667
        23  238.333333   4.341667   5.037500   16.120833
        24  200.869565   3.326087   3.821739   18.100000
        25  175.416667   7.508333   8.850000   20.637500
        26  233.333333   5.775000   6.858333   25.087500
        27  205.000000   5.112500   6.116667   23.991667
        28  235.652174   8.417391  10.804348   23.317391
        29  259.583333   5.916667   7.520833   19.012500
        30  232.083333   5.820833   6.708333   17.595833
     7  1   189.583333   4.370833   5.350000   20.933333
        2   210.416667   9.133333  11.350000   65.183333
        3   269.130435   9.508696  11.200000   17.239130
        4   197.500000   4.591667   5.158333   16.354167
        5    98.750000   2.975000   3.304167   18.358333
        6   157.500000   5.545833   6.558333   21.158333
        7   196.666667   8.216667   9.645833   25.254167
        8   212.500000   8.045833   9.695833   24.537500
        9   217.500000   5.675000   6.608333   21.620833
        10  206.666667   4.891667   6.262500   24.008333
        11  196.666667   7.400000   8.645833   20.833333
        12  217.500000   8.675000  10.533333   23.450000
        13  266.250000   9.066667  11.266667   21.629167
        14  203.478261   6.100000   7.186957   21.052174
        15  177.500000   5.420833   6.741667   23.720833
        16  213.333333   5.791667   7.383333   26.933333
        17  205.217391   4.965217   6.313043   24.743478
        18  181.666667   6.716667   8.025000   25.458333
        19  213.333333   3.379167   4.083333   22.754167
        20  211.666667   4.041667   4.833333   21.379167
        21  241.739130   5.052174   5.847826   22.847826
        22  118.636364   5.568182   6.531818   19.872727
        23  289.583333   7.883333   8.987500   19.533333
        24  240.416667   3.720833   4.220833   21.208333
        25  182.500000   5.004167   6.083333   21.725000
        26  222.916667   5.258333   6.083333   23.875000
        27  246.521739   4.178261   5.213043   23.660870
        28  139.166667   3.641667   4.275000   23.375000
        29  130.869565   4.821739   5.308696   23.134783
        30  189.166667   6.737500   7.970833   24.983333
        31  236.250000   4.545833   5.241667   24.483333
     8  1   202.500000   3.354167   3.970833   24.641667
        2   164.782609   6.060870   7.060870   22.521739
        3    92.916667   4.191667   4.937500   22.187500
        4   171.250000   7.450000   8.937500   64.558333
        5   192.500000   5.079167   6.408333   23.212500
        6   233.333333   4.091667   4.758333   23.612500
        7   238.636364   7.277273   8.522727   21.681818
        8   132.173913   5.595652   6.669565   21.030435
        9   209.545455   5.218182   6.440909   21.481818
        10  154.705882   9.088235  10.664706   18.905882
        11   42.000000   5.020000   5.980000   19.820000
        12  133.478261   3.191304   3.873913   20.291304
        13  150.833333   3.737500   4.487500   20.966667
        14  130.000000   4.308696   4.965217   20.513043
        15  105.833333   6.670833   7.704167   20.625000
        16  225.416667   4.233333   4.920833   21.325000
        17  245.000000   5.883333   7.225000   23.483333
        18  233.750000   5.616667   6.733333   24.162500
        19  256.521739   5.139130   5.904348   22.769565
        20   78.750000   5.879167   6.841667   21.175000
        21   97.916667   5.675000   6.458333   21.912500
        22  167.916667   8.083333   9.508333   24.308333
        23  195.833333   7.745833   9.504167   25.566667
        24  248.750000   6.600000   7.820833   21.745833
        25   31.666667   8.300000   9.987500   18.945833
        26   64.583333   8.512500   9.916667   19.091667
        27  108.750000   5.554167   6.525000   20.712500
        28  143.043478   4.247826   4.926087   21.752174
        29  225.000000   5.020833   5.700000   22.750000
        30  168.750000   3.500000   4.058333   22.641667
        31  163.333333   2.920833   3.408333   23.579167
     9  1   115.416667   5.920833   6.812500   23.475000
        2   122.500000   5.554167   6.316667   23.679167
        3   280.416667   6.962500   8.058333   22.966667
        4    45.416667   9.933333  11.400000   18.933333
        5   276.250000   8.670833  10.237500   17.595833
        6   174.782609   2.626087   3.352174   18.739130
        7   254.166667   4.937500   6.125000   18.891667
        8   252.500000   5.733333   6.962500   17.829167
        9   272.173913   7.047826   8.491304   14.060870
        10   93.636364   5.090909   6.545455   17.336364
        11  132.727273   8.245455   9.977273   19.213636
        12  213.636364   5.909091   7.413636   21.845455
        13  184.782609   7.208696   8.813043   21.565217
        14  205.833333   9.050000  10.983333   20.404167
        15  318.000000   7.305000   8.835000   15.485000
        16  270.000000   4.604545   5.800000   16.318182
        17  195.833333   7.441667   9.050000   19.287500
        18   73.181818   6.695455   7.700000   19.081818
        19  137.826087   7.491304   8.547826   19.204348
        20  186.086957   3.647826   4.204348   20.969565
        21  187.500000   3.862500   4.416667   20.266667
        22  106.666667   4.985714   5.857143   20.028571
        23  122.916667   7.050000   8.066667   20.779167
        24  155.416667   5.279167   5.916667   21.908333
        25  122.083333   4.091667   4.666667   20.733333
        26   99.166667   3.625000   4.262500   19.837500
        27   90.000000   3.095652   3.595652   20.291304
        28   94.583333   5.658333   6.516667   19.362500
        29  126.818182   5.618182   6.586364   17.295455
        30  298.333333   6.945833   8.479167   14.170833
     10 1   316.666667   9.929167  11.895833   11.908333
        2   286.250000   8.225000  10.037500   11.700000
        3   180.833333   6.679167   8.366667   13.045833
        4    96.086957   3.991304   5.234783   11.726087
        5   117.727273   5.786364   7.054545   13.677273
        6   109.166667   8.741667   9.937500   16.300000
        7   131.666667   9.683333  11.500000   15.991667
        8   218.750000   8.491667  10.158333   15.433333
        9   247.916667   6.179167   7.416667   15.825000
        10  161.666667   4.379167   5.100000   16.329167
        11  122.500000   6.375000   7.308333   17.450000
        12  134.166667   5.012500   5.487500   19.350000
        13  171.739130   6.921739   7.782609   20.808696
        14  226.521739   7.386957   9.004348   17.095652
        15  211.304348   4.869565   5.778261   14.965217
        16  309.583333   8.250000   9.804167   10.754167
        17  110.952381   5.557143   7.085714   11.733333
        18  187.500000   4.033333   5.258333   12.183333
        19  168.095238   9.090476  10.719048   12.985714
        20  237.083333   8.904167  10.666667   12.541667
        21  283.043478   8.091304   9.760870   10.152174
        22  100.454545   9.427273  11.422727    9.100000
        23  115.238095  12.290476  14.380952   10.219048
        24  170.416667   7.137500   8.675000   11.879167
        25  216.956522   8.300000  10.930435    8.478261
        26  237.916667  13.816667  17.845833   10.904167
        27  292.916667  11.704167  14.616667    5.016667
        28  304.782609   9.221739  11.195652    3.591304
        29  274.285714   7.761905   9.390476    4.976190
        30  177.500000   7.575000   8.730000    8.560000
        31  203.333333   9.141667  10.816667   14.583333
     11 1   161.739130   5.521739   6.291304   11.839130
        2   100.000000   6.531818   7.413636   11.477273
        3   192.916667   7.987500   9.395833   17.412500
        4   187.826087   9.030435  10.069565   16.800000
        5   177.500000   8.812500   9.845833   15.704167
        6   162.608696   9.960870  11.234783   14.673913
        7   198.750000   9.033333  11.225000    9.875000
        8   231.739130  10.408696  14.069565    3.560870
        9   279.090909   8.850000  11.127273    2.413636
        10  255.416667   6.933333   9.137500   -0.220833
        11  197.692308   5.515385   7.123077    2.884615
        12  155.909091  10.427273  12.513636    5.690909
        13  200.000000   9.529167  11.508333    9.087500
        14  243.181818   8.427273  10.040909   10.036364
        15  336.666667  12.376190  14.647619    5.390476
        16  274.166667   9.150000  11.550000    1.245833
        17  304.761905   8.961905  10.928571    0.342857
        18  308.333333   9.279167  11.279167   -2.066667
        19  208.695652   9.247826  11.152174    1.326087
        20  320.434783  12.173913  14.521739    0.752174
        21  300.869565   9.886957  12.060870   -4.356522
        22  225.000000   6.479167   8.050000   -2.933333
        23  187.272727   8.131818   9.504545    0.318182
        24  240.000000   7.929167   9.512500    2.858333
        25  302.500000   9.362500  11.129167    1.033333
        26  251.250000   3.425000   4.116667    1.462500
        27  251.818182   3.454545   4.281818    3.359091
        28  269.090909   8.363636  10.336364    2.395455
        29  224.347826   4.052174   4.726087    2.513043
        30   76.666667   8.883333  10.058333    3.391667
     12 1   203.333333  12.458333  15.254167   -0.562500
        2   240.000000   9.420833  11.904167   -3.962500
        3   216.956522  11.130435  13.382609    2.004348
        4   287.391304   8.643478  10.547826   -5.560870
        5   259.583333   8.737500  11.029167   -9.416667
        6   234.736842  12.463158  15.126316   -3.700000
        7   275.652174   8.413043  10.343478   -8.804348
        8   166.956522   7.991304   9.786957   -3.886957
        9   185.000000   7.358333   8.791667    2.995833
        10  290.869565  11.913043  13.878261   -2.500000
        11  254.166667   5.362500   6.470833   -2.116667
        12  299.166667   7.633333   9.379167   -6.845833
        13  192.916667  11.679167  13.962500   -2.637500
        14  187.916667  15.787500  18.966667    5.200000
        15  243.333333  13.683333  17.141667   -5.045833
        16  257.222222   6.361111   8.061111  -10.116667
        17  225.416667   6.820833   8.445833   -6.691667
        18  222.500000   2.991667   4.066667   -8.400000
        19   74.166667   9.095833  10.683333   -2.683333
        20   84.583333   8.566667  10.170833   -2.750000
        21  236.250000  14.995833  18.287500  -14.016667
        22  266.111111  11.438889  14.300000  -17.527778
        30  117.142857   6.385714   7.428571    1.271429
        31  310.833333   9.270833  11.629167   -5.687500

In [54]:
data_2008.dtypes

#YY       int64
MM        int64
DD        int64
hh        int64
mm        int64
WDIR      int64
WSPD    float64
GST     float64
ATMP    float64
DEWP     object
dtype: object

In [55]:
# this shows that the there are missing values January, February, March, April, May, and December.
nov_2008 = data_2008[data_2008['MM'] == 11.0]
for i in range(1, 13):
    print(i, len(data_2008[data_2008['MM'] == i]['DD'].value_counts()))

1 20
2 0
3 0
4 0
5 0
6 30
7 31
8 31
9 30
10 31
11 30
12 24

In [56]:
nov_2008 = data_2008[data_2008['MM'] == 11]

In [57]:
# There are no missing values in November.
for i in range(1, 31):
    print(i, len(nov_2008[nov_2008['DD'] == i]))

1 23
2 22
3 24
4 23
5 24
6 23
7 24
8 23
9 22
10 24
11 13
12 22
13 24
14 22
15 21
16 24
17 21
18 24
19 23
20 23
21 23
22 24
23 22
24 24
25 24
26 24
27 22
28 22
29 23
30 24

<a id='2009'></a>

### Exploring the data for 2009.

In [58]:
data_09 = pd.read_csv('../data/buoy_CHII2/chii2h2009.csv')
print(data_09.shape)
data_09.head()

(8288, 18)

,#YY,MM,DD,hh,mm,WDI,R WSP,D GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,TIDE
0,2009,1,1,0,0,280,2.6,3.6,99,99,99,999,9999,-6.6,999,999,99,99
1,2009,1,1,1,0,260,3.1,4.1,99,99,99,999,9999,-6.7,999,999,99,99
2,2009,1,1,2,0,270,4.1,5.1,99,99,99,999,9999,-7.3,999,999,99,99
3,2009,1,1,3,0,270,4.6,5.7,99,99,99,999,9999,-7.7,999,999,99,99
4,2009,1,1,4,0,260,2.6,4.6,99,99,99,999,9999,-7.4,999,999,99,99

In [59]:
data_09.rename(mapper={
    'WDI': 'WDIR',
    'R WSP': 'WSPD',
    'D GST': 'GST'
}, axis=1, inplace=True)
data_09.head()

,#YY,MM,DD,hh,mm,WDIR,WSPD,GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,TIDE
0,2009,1,1,0,0,280,2.6,3.6,99,99,99,999,9999,-6.6,999,999,99,99
1,2009,1,1,1,0,260,3.1,4.1,99,99,99,999,9999,-6.7,999,999,99,99
2,2009,1,1,2,0,270,4.1,5.1,99,99,99,999,9999,-7.3,999,999,99,99
3,2009,1,1,3,0,270,4.6,5.7,99,99,99,999,9999,-7.7,999,999,99,99
4,2009,1,1,4,0,260,2.6,4.6,99,99,99,999,9999,-7.4,999,999,99,99

### Exploring the data for 2010.

In [60]:
data_10 = pd.read_csv('../data/buoy_CHII2/chii2h2010.csv')
print(data_10.shape)
data_10.head()

(8466, 18)

,#YY,MM,DD,hh,mm,WDI,R WSP,D GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,TIDE
0,2010,1,1,0,0,320,11.8,13.9,99,99,99,999,9999,-7.5,999,999,99,99
1,2010,1,1,1,0,300,9.8,12.9,99,99,99,999,9999,-8.5,999,999,99,99
2,2010,1,1,2,0,300,10.3,13.4,99,99,99,999,9999,-8.5,999,999,99,99
3,2010,1,1,3,0,300,10.3,13.4,99,99,99,999,9999,-9.0,999,999,99,99
4,2010,1,1,4,0,300,9.3,12.4,99,99,99,999,9999,-9.5,999,999,99,99

In [61]:
data_10.rename(mapper={
    'WDI': 'WDIR',
    'R WSP': 'WSPD',
    'D GST': 'GST'
}, axis=1, inplace=True)
data_10.head()

,#YY,MM,DD,hh,mm,WDIR,WSPD,GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,TIDE
0,2010,1,1,0,0,320,11.8,13.9,99,99,99,999,9999,-7.5,999,999,99,99
1,2010,1,1,1,0,300,9.8,12.9,99,99,99,999,9999,-8.5,999,999,99,99
2,2010,1,1,2,0,300,10.3,13.4,99,99,99,999,9999,-8.5,999,999,99,99
3,2010,1,1,3,0,300,10.3,13.4,99,99,99,999,9999,-9.0,999,999,99,99
4,2010,1,1,4,0,300,9.3,12.4,99,99,99,999,9999,-9.5,999,999,99,99

### Exploring the data for 2011.

In [62]:
data_11 = pd.read_csv('../data/buoy_CHII2/chii2h2011.csv')
print(data_11.shape)
data_11.head()

(8499, 18)

,#YY,MM,DD,hh,mm,WDI,R WSP,D GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,TIDE
0,2011,1,1,0,0,180,12.4,13.4,99,99,99,999,9999,11.1,999,999,99,99
1,2011,1,1,1,0,180,9.8,11.3,99,99,99,999,9999,9.8,999,999,99,99
2,2011,1,1,2,0,200,10.8,11.3,99,99,99,999,9999,11.8,999,999,99,99
3,2011,1,1,3,0,190,10.3,11.3,99,99,99,999,9999,10.9,999,999,99,99
4,2011,1,1,4,0,200,11.3,12.9,99,99,99,999,9999,12.2,999,999,99,99

In [63]:
data_11.rename(mapper={
    'WDI': 'WDIR',
    'R WSP': 'WSPD',
    'D GST': 'GST'
}, axis=1, inplace=True)
data_11.head()

,#YY,MM,DD,hh,mm,WDIR,WSPD,GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,TIDE
0,2011,1,1,0,0,180,12.4,13.4,99,99,99,999,9999,11.1,999,999,99,99
1,2011,1,1,1,0,180,9.8,11.3,99,99,99,999,9999,9.8,999,999,99,99
2,2011,1,1,2,0,200,10.8,11.3,99,99,99,999,9999,11.8,999,999,99,99
3,2011,1,1,3,0,190,10.3,11.3,99,99,99,999,9999,10.9,999,999,99,99
4,2011,1,1,4,0,200,11.3,12.9,99,99,99,999,9999,12.2,999,999,99,99

### Exploring the data for 2012.

In [64]:
data_12 = pd.read_csv('../data/buoy_CHII2/chii2h2012.csv')
print(data_12.shape)
data_12.head()

(8589, 18)

,#YY,MM,DD,hh,mm,WDI,R WSP,D GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,TIDE
0,2012,1,1,0,0,170,12.9,16.0,99,99,99,999,9999,2.9,999,999,99,99
1,2012,1,1,1,0,170,13.9,16.5,99,99,99,999,9999,3.0,999,999,99,99
2,2012,1,1,2,0,170,14.4,16.5,99,99,99,999,9999,3.2,999,999,99,99
3,2012,1,1,3,0,180,12.4,14.4,99,99,99,999,9999,3.7,999,999,99,99
4,2012,1,1,4,0,170,9.3,9.8,99,99,99,999,9999,3.9,999,999,99,99

In [65]:
data_12.rename(mapper={
    'WDI': 'WDIR',
    'R WSP': 'WSPD',
    'D GST': 'GST'
}, axis=1, inplace=True)
data_12.head()

,#YY,MM,DD,hh,mm,WDIR,WSPD,GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,TIDE
0,2012,1,1,0,0,170,12.9,16.0,99,99,99,999,9999,2.9,999,999,99,99
1,2012,1,1,1,0,170,13.9,16.5,99,99,99,999,9999,3.0,999,999,99,99
2,2012,1,1,2,0,170,14.4,16.5,99,99,99,999,9999,3.2,999,999,99,99
3,2012,1,1,3,0,180,12.4,14.4,99,99,99,999,9999,3.7,999,999,99,99
4,2012,1,1,4,0,170,9.3,9.8,99,99,99,999,9999,3.9,999,999,99,99

### Exploring the data for 2013.

In [66]:
data_13 = pd.read_csv('../data/buoy_CHII2/chii2h2013.csv')
print(data_13.shape)
data_13.head()

(30419, 18)

,#YY,MM,DD,hh,mm,WDIR,WSP,D GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,TIDE
0,2013,1,1,0,0,330,4.1,5.1,99,99,99,999,9999,-2.6,999,999,99,99
1,2013,1,1,1,0,330,5.1,6.2,99,99,99,999,9999,-3.0,999,999,99,99
2,2013,1,1,2,0,340,8.8,10.3,99,99,99,999,9999,-3.7,999,999,99,99
3,2013,1,1,3,0,350 1,0.3,12.4,99,99,99,999,9999,-5.1,999,999,99,99
4,2013,1,1,4,0,330,9.3,10.8,99,99,99,999,9999,-5.6,999,999,99,99

In [67]:
data_13.rename(mapper={
    'WDI': 'WDIR',
    'R WSP': 'WSPD',
    'D GST': 'GST'
}, axis=1, inplace=True)
data_13.head()

,#YY,MM,DD,hh,mm,WDIR,WSP,GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,TIDE
0,2013,1,1,0,0,330,4.1,5.1,99,99,99,999,9999,-2.6,999,999,99,99
1,2013,1,1,1,0,330,5.1,6.2,99,99,99,999,9999,-3.0,999,999,99,99
2,2013,1,1,2,0,340,8.8,10.3,99,99,99,999,9999,-3.7,999,999,99,99
3,2013,1,1,3,0,350 1,0.3,12.4,99,99,99,999,9999,-5.1,999,999,99,99
4,2013,1,1,4,0,330,9.3,10.8,99,99,99,999,9999,-5.6,999,999,99,99

In [68]:
data_13.dtypes

#YY       int64
MM        int64
DD        int64
hh        int64
mm        int64
WDIR     object
WSP     float64
GST     float64
WVHT      int64
DPD       int64
APD       int64
MWD       int64
PRES      int64
ATMP    float64
WTMP      int64
DEWP      int64
VIS       int64
TIDE      int64
dtype: object

<a id='2014'></a>
### Exploring the data for 2014.

### Table of contents

Exploring the data:  
[2005](#2005), 
[2006](#2006), 
[2007](#2007),  
[2008](#2008)  
[2009](#2009)  
[2010](#2010)  
[2011](#2011)  
[2012](#2012)  
[2013](#2013)  
[2014](#2014), 
[2015](#2015),
[2016](#2016), 
[2017](#2017), 
[2018](#2018), 
[2019](#2019) 

#### Missing data
 - [Dec 5-13, 2015](#Dec5-13,2015)
 - [Nov. 30, 2016](#Nov30,2016)
 - [Dec 25, 2017](#Dec25,2017)
 - [Dec. 27-31, 2018](#Dec27-31,2018)

In [69]:
data_14 = pd.read_csv('../data/buoy_CHII2/chii2h2014.csv')
print(data_14.shape)
data_14.head()

(33141, 18)

,#YY,MM,DD,hh,mm,WDIR,WSPD,GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,TIDE
0,2014,1,1,0,0,280,2.6,3.6,99,99,99,999,9999,-10.4,999,999,99,99
1,2014,1,1,0,30,310,2.1,3.6,99,99,99,999,9999,-10.4,999,999,99,99
2,2014,1,1,0,45,290,3.1,4.1,99,99,99,999,9999,-10.4,999,999,99,99
3,2014,1,1,1,0,280,3.1,3.6,99,99,99,999,9999,-10.3,999,999,99,99
4,2014,1,1,1,15,290,3.1,4.1,99,99,99,999,9999,-10.3,999,999,99,99

In [70]:
data_14.dtypes

#YY       int64
MM        int64
DD        int64
hh        int64
mm        int64
WDIR     object
WSPD     object
GST     float64
WVHT      int64
DPD       int64
APD       int64
MWD       int64
PRES      int64
ATMP    float64
WTMP      int64
DEWP      int64
VIS       int64
TIDE      int64
dtype: object

### Cleaning the 'WDIR' feature

In [137]:
series = data_14['WDIR']

In [139]:
data0 = []
j = 0 
for i in range(len(data_14['WDIR'])):
    if i % 1000 == 0:
        j += i
        print(f'Checking item {i}')
    
    if len(series.iloc[i].split()) == 1:
        pass
    else:
        data0 = series.iloc[i]
        data1 = data0.split()
        series.iloc[i] = data1[0]

Checking item 0
Checking item 1000
Checking item 2000
Checking item 3000
Checking item 4000
Checking item 5000
Checking item 6000
Checking item 7000
Checking item 8000
Checking item 9000
Checking item 10000
Checking item 11000
Checking item 12000
Checking item 13000
Checking item 14000
Checking item 15000
Checking item 16000
Checking item 17000
Checking item 18000
Checking item 19000
Checking item 20000
Checking item 21000
Checking item 22000
Checking item 23000
Checking item 24000
Checking item 25000
Checking item 26000
Checking item 27000
Checking item 28000
Checking item 29000
Checking item 30000
Checking item 31000
Checking item 32000
Checking item 33000

In [140]:
data_14['WDIR'] = series
data_14['WDIR'].head()

0    280
1    310
2    290
3    280
4    290
Name: WDIR, dtype: object

In [143]:
for i in range(len(data_14['WDIR'])):
    if len(data_14['WDIR'].loc[i].split()) == 1:
        pass
    else:
        print(i, data_14['WDIR'].loc[i].split())
print('Everything checks out.')

Everything checks out.

In [144]:
data_14['WDIR'] = data_14['WDIR'].astype('int')

### Cleaning the 'WSPD' feature

In [166]:
data_14['WSPD'].iloc[35: 50]

35      6.7
36      7.2
37      7.7
38      7.2
39      8.2
40    9.8 1
41    9.8 1
42    8.8 1
43    9.3 1
44    9.3 1
45    9.8 1
46    0.8 1
47    0.3 1
48    0.3 1
49    0.3 1
Name: WSPD, dtype: object

In [167]:
wspd = data_14['WSPD']

In [170]:
start_time = time.time()

data0 = []
j = 0 
for i in range(len(wspd)):
    if i % 1000 == 0:
        j += i
        print(f'{100 - 100 * i/ len(wspd)}% left until complete')
    
    if len(wspd.iloc[i].split()) == 1:
        pass
    else:
        data0 = wspd.iloc[i]
        data1 = data0.split()
        wspd.iloc[i] = data1[0]
        
end_time = round(time.time() - start_time, 3)
print(f'time: {end_time} seconds')
end_time_minutes = int(end_time/ 60)
end_time_seconds = round(end_time % 60, 3)  

print(f'time: {end_time_minutes} minutes, {end_time_seconds} seconds')

100.0% left until complete
96.98258954165536% left until complete
93.9651790833107% left until complete
90.94776862496606% left until complete
87.9303581666214% left until complete
84.91294770827676% left until complete
81.8955372499321% left until complete
78.87812679158746% left until complete
75.8607163332428% left until complete
72.84330587489816% left until complete
69.82589541655352% left until complete
66.80848495820887% left until complete
63.791074499864216% left until complete
60.77366404151957% left until complete
57.75625358317492% left until complete
54.73884312483027% left until complete
51.72143266648562% left until complete
48.70402220814098% left until complete
45.68661174979633% left until complete
42.66920129145168% left until complete
39.65179083310703% left until complete
36.63438037476238% left until complete
33.61696991641773% left until complete
30.599559458073088% left until complete
27.58214899972843% left until complete
24.56473854138379% left until complete
21.547328083039133% left until complete
18.52991762469449% left until complete
15.512507166349835% left until complete
12.495096708005192% left until complete
9.477686249660536% left until complete
6.460275791315894% left until complete
3.4428653329712375% left until complete
0.42545487462659537% left until complete
time: 3052.297 seconds
time: 50 minutes, 52.297 seconds

In [171]:
data_14['WSPD'] = wspd
data_14['WSPD'].head()

0    2.6
1    2.1
2    3.1
3    3.1
4    3.1
Name: WSPD, dtype: object

In [175]:
for i in range(len(data_14['WSPD'])):
    if len(data_14['WSPD'].loc[i].split()) == 1:
        pass
    else:
        print(i, data_14['WSPD'].loc[i].split())
print('Everything checks out.')

Everything checks out.

In [177]:
data_14['WSPD'] = data_14['WSPD'].astype('float')

In [178]:
data_2014 = data_14[features]

In [179]:
# saving the 2017 chii2 buoy data to a csv.
data_2014.to_csv('../data/buoy_CHII2/chii2_buoy_data_2014.csv')

In [180]:
# print(len(data_2017.groupby(['#YY', 'MM', 'DD']).mean().drop(['hh', 'mm'], axis=1)))
data_2014.groupby(['#YY', 'MM', 'DD']).mean().drop(['hh', 'mm'], axis=1).head()

                  WDIR      WSPD       GST       ATMP   DEWP
#YY  MM DD
2014 1  1   113.294118  4.143529  4.822353  -7.041176  999.0
        2    69.512195  2.452439  3.840244  -6.847561  999.0
        3   253.292683  5.176829  5.548780 -12.076829  999.0
        4   194.597701  5.387356  4.114943  -4.341379  999.0
        5   316.626506  5.042169  4.374699  -4.050602  999.0

In [181]:
# checking to see which months are missing days
for i in range(1, 13):
    print(i, len(data_2014[data_2017['MM'] == i]['DD'].value_counts()))

1 31
2 31
3 30
4 31
5 31
6 31
7 31
8 31
9 0
10 0
11 0
12 0

/Users/blakewallace/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  This is separate from the ipykernel package so we can avoid doing imports until

<a id='2015'></a>
### Exploring the data for 2015.

#### Missing data
[Dec 5-13, 2015](#Dec5-13,2015)

In [71]:
data_15 = pd.read_csv('../data/buoy_CHII2/chii2h2015.csv')
print(data_15.shape)
data_15.head()

(34570, 18)

,#YY,MM,DD,hh,mm,WDIR,WSPD,GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,TIDE
0,2015,1,1,0,0,220,10.8,13.9,99,99,99,999,9999,-7.2,999,999.0,99,99
1,2015,1,1,0,15,220,11.8,15.4,99,99,99,999,9999,-7.2,999,999.0,99,99
2,2015,1,1,0,30,220,11.8,17.0,99,99,99,999,9999,-7.1,999,999.0,99,99
3,2015,1,1,0,45,220,12.4,17.0,99,99,99,999,9999,-6.9,999,999.0,99,99
4,2015,1,1,1,0,220,12.9,19.0,99,99,99,999,9999,-7.0,999,999.0,99,99

In [72]:
data_15.dtypes

#YY       int64
MM        int64
DD        int64
hh        int64
mm        int64
WDIR      int64
WSPD    float64
GST     float64
WVHT      int64
DPD       int64
APD       int64
MWD       int64
PRES      int64
ATMP    float64
WTMP      int64
DEWP    float64
VIS       int64
TIDE      int64
dtype: object

In [112]:
data_2015 = data_15[features]
print(data_2015.shape)
data_2015.head()

(34570, 10)

    #YY  MM  DD  hh  mm  WDIR  WSPD   GST  ATMP   DEWP
0  2015   1   1   0   0   220  10.8  13.9  -7.2  999.0
1  2015   1   1   0  15   220  11.8  15.4  -7.2  999.0
2  2015   1   1   0  30   220  11.8  17.0  -7.1  999.0
3  2015   1   1   0  45   220  12.4  17.0  -6.9  999.0
4  2015   1   1   1   0   220  12.9  19.0  -7.0  999.0

In [113]:
print(len(data_2015.groupby(['#YY', 'MM', 'DD']).mean().drop(['hh', 'mm'], axis=1)))
data_2015.groupby(['#YY', 'MM', 'DD']).mean().drop(['hh', 'mm'], axis=1).head()

356

                  WDIR       WSPD        GST       ATMP   DEWP
#YY  MM DD
2015 1  1   232.083333  10.191667  14.289583  -6.083333  999.0
        2   220.000000   5.331250   6.541667  -2.022917  999.0
        3   168.229167   4.597917   5.357292   0.307292  999.0
        4   314.062500   7.702083   9.019792  -1.535417  999.0
        5   270.625000   9.589583  12.181250 -15.468750  999.0

In [114]:
# checking to see which months are missing days
for i in range(1, 13):
    print(i, len(data_2015[data_2015['MM'] == i]['DD'].value_counts()))

1 31
2 28
3 31
4 30
5 31
6 30
7 31
8 31
9 30
10 31
11 30
12 22

<a id='Dec5-13,2015'></a>

In [116]:
# missing data, Dec. 5-13, 2015
data_2015.groupby(['#YY', 'MM', 'DD']).mean().drop(['hh', 'mm'], axis=1).tail(20)

                  WDIR       WSPD        GST      ATMP        DEWP
#YY  MM DD
2015 12 3   276.875000   7.585417   9.529167  1.207292  999.000000
        4   236.557377   6.575410   8.780328  1.632787  999.000000
        14  203.125000  10.662500  12.768750  9.831250  999.000000
        15  187.301587   5.646825   6.633333  6.005556  832.679365
        16  151.532847  10.159124  11.724818  7.272263    4.477372
        17  247.021277  10.136170  11.895035  1.838298   -3.854610
        18  259.718310   8.914085  10.582394 -0.924648   -7.611268
        19  264.861111   8.551389   9.996528 -3.352778   -9.756250
        20  195.138889  11.464583  12.726389  3.779861   -3.752778
        21  214.236111  12.613194  14.398611  8.756944    5.384722
        22  267.291667   4.906944   5.531944  4.784028    3.683333
        23  158.142857   9.997143  11.050000  8.672857    7.923571
        24  225.070423  11.043662  12.904930  6.583099    1.866901
        25  225.633803   5.438028   6.083803  5.221831    1.940141
        26   79.084507   8.377465   9.200704  5.735211    3.129577
        27  169.577465  11.540141  12.876056  5.197183    3.426056
        28   61.875000  15.024306  16.799306  2.077083   -0.904167
        29  218.958333   9.865278  11.406944  2.620139    0.922917
        30  248.611111   5.601389   6.494444 -0.728472   -3.686111
        31  261.544118   7.882353   9.211765 -2.132353   -5.861029

In [119]:
data_2015.head()

    #YY  MM  DD  hh  mm  WDIR  WSPD   GST  ATMP   DEWP
0  2015   1   1   0   0   220  10.8  13.9  -7.2  999.0
1  2015   1   1   0  15   220  11.8  15.4  -7.2  999.0
2  2015   1   1   0  30   220  11.8  17.0  -7.1  999.0
3  2015   1   1   0  45   220  12.4  17.0  -6.9  999.0
4  2015   1   1   1   0   220  12.9  19.0  -7.0  999.0

<a id='2016'></a>
### Exploring the data for 2016.

#### Missing data
[Nov. 30, 2016](#Nov30,2016)

In [73]:
data_16 = pd.read_csv('../data/buoy_CHII2/chii2h2016.csv')
print(data_16.shape)
data_16.head()

(51583, 18)

,#YY,MM,DD,hh,mm,WDIR,WSPD,GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,TIDE
0,2016,1,1,0,0,250,9.8,11.3,99,99,99,999,9999,-2.4,999,-6.9,99,99
1,2016,1,1,0,10,240,8.8,10.8,99,99,99,999,9999,-2.4,999,-6.7,99,99
2,2016,1,1,0,20,270,8.8,10.3,99,99,99,999,9999,-2.2,999,-6.3,99,99
3,2016,1,1,0,30,260,7.2,8.2,99,99,99,999,9999,-2.2,999,-6.1,99,99
4,2016,1,1,0,40,270,8.2,9.3,99,99,99,999,9999,-2.4,999,-6.3,99,99

In [74]:
data_16.dtypes

#YY       int64
MM        int64
DD        int64
hh        int64
mm        int64
WDIR      int64
WSPD    float64
GST     float64
WVHT      int64
DPD       int64
APD       int64
MWD       int64
PRES      int64
ATMP    float64
WTMP      int64
DEWP    float64
VIS       int64
TIDE      int64
dtype: object

In [75]:
data_2016 = data_16[features]
print(data_2016.shape)
data_2016.head()

(51583, 10)

    #YY  MM  DD  hh  mm  WDIR  WSPD   GST  ATMP  DEWP
0  2016   1   1   0   0   250   9.8  11.3  -2.4  -6.9
1  2016   1   1   0  10   240   8.8  10.8  -2.4  -6.7
2  2016   1   1   0  20   270   8.8  10.3  -2.2  -6.3
3  2016   1   1   0  30   260   7.2   8.2  -2.2  -6.1
4  2016   1   1   0  40   270   8.2   9.3  -2.4  -6.3

In [76]:
print(len(data_2016.groupby(['#YY', 'MM', 'DD']).mean().drop(['hh', 'mm'], axis=1)))
data_2016.groupby(['#YY', 'MM', 'DD']).mean().drop(['hh', 'mm'], axis=1).head()

364

                  WDIR      WSPD        GST      ATMP      DEWP
#YY  MM DD
2016 1  1   252.000000  9.413571  11.295714 -3.380000 -7.514286
        2   248.601399  7.246853   8.623077 -0.991608 -5.634266
        3   300.567376  9.843972  11.155319 -1.019149 -5.549645
        4   221.111111  9.327778  10.625694 -1.409722 -6.588889
        5   161.875000  7.882639   8.947222 -1.968056 -6.581250

In [77]:
# checking to see which months are missing days
for i in range(1, 13):
    print(i, len(data_2016[data_2016['MM'] == i]['DD'].value_counts()))

1 31
2 29
3 31
4 30
5 31
6 30
7 31
8 31
9 30
10 31
11 29
12 30

<a id='Nov30,2016'></a>

In [78]:
# missing data, Nov. 30, 2016
data_2016.groupby(['#YY', 'MM', 'DD']).mean().drop(['hh', 'mm'], axis=1).tail(31)

                  WDIR       WSPD        GST       ATMP       DEWP
#YY  MM DD
2016 11 29  201.509434  11.606604  13.133962  10.160377   7.505660
     12 1   262.380952   9.968254  11.492063   4.822222   1.128571
        2   290.661765   6.722794   7.754412   4.061765  -0.605147
        3   290.000000   4.265278   5.179861   1.820139  -4.464583
        4   190.069444   3.270833   4.004167   1.681944  -2.068750
        5   234.097222   6.974306   8.056944   1.435417   0.190972
        6   165.177305   6.448936   7.458156   3.535461   1.037589
        7   257.916667  10.124306  11.851389  -1.450000  -6.643750
        8   271.736111  12.561806  14.530556  -4.947917  -9.446528
        9   282.553191   8.238298   9.552482  -3.839716  -8.427660
        11  187.173913   8.436957   9.143478   0.530435  -0.326087
        12  255.555556   8.115278   9.349306  -2.241667  -4.582639
        13  264.583333   6.736111   7.813889  -6.076389 -11.126389
        14  262.291667  10.577778  12.215278  -9.388194 -15.744444
        15  276.319444  10.691667  12.486111 -13.444444 -19.130556
        16  206.028369   8.222695   9.556028  -8.704965 -14.983688
        17  265.343511   5.624427   6.428244  -4.439695  -6.407634
        18  300.763889   9.448611  10.815972  -9.348611 -12.763194
        19  232.708333   8.592361   9.723611 -14.715278 -20.261806
        20  212.986111  12.360417  14.245833  -5.156944 -12.229861
        21  217.777778   7.738889   8.781944  -0.558333  -5.473611
        22  272.638889   7.242361   8.087500   2.839583  -2.826389
        23  198.819444   7.006250   7.711806   1.151389  -2.245139
        24  228.541667   4.795139   5.394444   2.322917   0.447222
        25  136.736111   6.720139   7.487500   1.545139   0.163889
        26  193.055556  11.109028  12.727083   7.860417   4.534722
        27  268.402778  10.634028  12.227778  -1.054861  -6.671528
        28  213.055556   8.029861   8.968056   1.186111  -3.672222
        29  268.055556  11.971528  13.711806   2.164583  -3.004167
        30  271.489362   9.334752  10.726241  -0.491489  -7.702837
        31  235.633803  12.351408  14.106338   3.271127  -5.119014

<a id='2017'></a>
### Exploring the data for 2017.

#### Missing data
[Dec 25, 2017](#Dec25,2017)

In [79]:
data_17 = pd.read_csv('../data/buoy_CHII2/chii2h2017.csv')
print(data_17.shape)
data_17.head()

(50474, 18)

,#YY,MM,DD,hh,mm,WDIR,WSPD,GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,TIDE
0,2017,1,1,0,0,280,8.8,10.3,99,99,99,999,9999,1.3,999,-6.2,99,99
1,2017,1,1,0,10,280,7.2,8.2,99,99,99,999,9999,1.2,999,-6.4,99,99
2,2017,1,1,0,20,280,7.2,7.7,99,99,99,999,9999,1.1,999,-6.2,99,99
3,2017,1,1,0,30,280,7.7,8.2,99,99,99,999,9999,1.0,999,-6.2,99,99
4,2017,1,1,0,40,280,7.7,8.8,99,99,99,999,9999,0.9,999,-6.3,99,99

In [80]:
data_17.dtypes

#YY       int64
MM        int64
DD        int64
hh        int64
mm        int64
WDIR     object
WSPD    float64
GST     float64
WVHT      int64
DPD       int64
APD       int64
MWD       int64
PRES      int64
ATMP    float64
WTMP      int64
DEWP    float64
VIS       int64
TIDE      int64
dtype: object

In [81]:
data_2017 = data_17[features]
print(data_2017.shape)
data_2017.head()

(50474, 10)

    #YY  MM  DD  hh  mm WDIR  WSPD   GST  ATMP  DEWP
0  2017   1   1   0   0  280   8.8  10.3   1.3  -6.2
1  2017   1   1   0  10  280   7.2   8.2   1.2  -6.4
2  2017   1   1   0  20  280   7.2   7.7   1.1  -6.2
3  2017   1   1   0  30  280   7.7   8.2   1.0  -6.2
4  2017   1   1   0  40  280   7.7   8.8   0.9  -6.3

### The 'WDIR' feature has some values in it with trailing 1.  We address this issue now.

In [82]:
# an example
data_2017['WDIR'].loc[50232] #.astype('int')

'290 1'

In [83]:
len(data_2017)

50474

In [84]:
data_2017['WDIR'].loc[50232].split()

['290', '1']

In [85]:
data_2017['WDIR'].loc[0]

'280'

In [86]:
data_2017['WDIR'].loc[0].split()

['280']

In [87]:
len(data_2017['WDIR'].loc[0].split())

1

In [88]:
for i in range(24000, 25000):
    
    print(i, data_2017['WDIR'].loc[i].split())

24000 ['290']
24001 ['290']
24002 ['290']
24003 ['290']
24004 ['280']
24005 ['280']
24006 ['280']
24007 ['280']
24008 ['290']
24009 ['280']
24010 ['280']
24011 ['280']
24012 ['280']
24013 ['270']
24014 ['270']
24015 ['270']
24016 ['260']
24017 ['260']
24018 ['270']
24019 ['270']
24020 ['270']
24021 ['260']
24022 ['260']
24023 ['260']
24024 ['260']
24025 ['260']
24026 ['270']
24027 ['270']
24028 ['260']
24029 ['270']
24030 ['280']
24031 ['270']
24032 ['270']
24033 ['270']
24034 ['280']
24035 ['280']
24036 ['280']
24037 ['280']
24038 ['280']
24039 ['280']
24040 ['280']
24041 ['290']
24042 ['280']
24043 ['280']
24044 ['270', '1']
24045 ['280']
24046 ['270']
24047 ['290']
24048 ['280']
24049 ['280']
24050 ['270']
24051 ['270']
24052 ['270']
24053 ['280', '1']
24054 ['290', '1']
24055 ['280']
24056 ['290']
24057 ['300']
24058 ['270']
24059 ['300']
24060 ['280', '1']
24061 ['290']
24062 ['290', '1']
24063 ['280']
24064 ['280']
24065 ['280']
24066 ['290']
24067 ['250']
24068 ['280', '1']
24069 ['270']
24070 ['270']
24071 ['280']
24072 ['260', '1']
24073 ['270']
24074 ['290']
24075 ['280']
24076 ['300']
24077 ['280']
24078 ['280']
24079 ['280']
24080 ['290']
24081 ['270']
24082 ['280']
24083 ['280']
24084 ['290']
24085 ['270']
24086 ['280']
24087 ['290']
24088 ['290']
24089 ['290']
24090 ['270']
24091 ['280', '1']
24092 ['270']
24093 ['280', '1']
24094 ['270']
24095 ['270', '1']
24096 ['270', '1']
24097 ['270']
24098 ['280']
24099 ['290', '1']
24100 ['280', '1']
24101 ['280', '1']
24102 ['270', '1']
24103 ['270', '1']
24104 ['290', '1']
24105 ['290', '1']
24106 ['290']
24107 ['300']
24108 ['280', '1']
24109 ['290', '1']
24110 ['290']
24111 ['290']
24112 ['290']
24113 ['290']
24114 ['290']
24115 ['280']
24116 ['290']
24117 ['280']
24118 ['280']
24119 ['280']
24120 ['280']
24121 ['280']
24122 ['280']
24123 ['300']
24124 ['320', '1']
24125 ['310']
24126 ['320']
24127 ['300']
24128 ['290']
24129 ['300']
24130 ['300']
24131 ['290']
24132 ['290']
24133 ['290']
24134 ['290']
24135 ['280']
24136 ['280']
24137 ['280']
24138 ['290']
24139 ['280']
24140 ['280']
24141 ['280']
24142 ['270']
24143 ['270']
24144 ['270']
24145 ['260']
24146 ['260']
24147 ['260']
24148 ['260']
24149 ['260']
24150 ['260']
24151 ['270']
24152 ['270']
24153 ['270']
24154 ['270']
24155 ['270']
24156 ['270']
24157 ['270']
24158 ['270']
24159 ['260']
24160 ['270']
24161 ['270']
24162 ['270']
24163 ['270']
24164 ['270']
24165 ['270']
24166 ['270']
24167 ['270']
24168 ['270']
24169 ['270']
24170 ['270']
24171 ['260']
24172 ['260']
24173 ['260']
24174 ['260']
24175 ['260']
24176 ['260']
24177 ['260']
24178 ['260']
24179 ['270']
24180 ['270']
24181 ['270']
24182 ['290']
24183 ['280']
24184 ['280']
24185 ['290']
24186 ['280']
24187 ['280']
24188 ['270']
24189 ['290']
24190 ['270']
24191 ['270']
24192 ['270']
24193 ['280', '1']
24194 ['280']
24195 ['280']
24196 ['270', '1']
24197 ['260']
24198 ['300']
24199 ['300']
24200 ['290']
24201 ['280']
24202 ['300']
24203 ['290']
24204 ['290']
24205 ['270']
24206 ['310']
24207 ['310']
24208 ['290', '1']
24209 ['290']
24210 ['290']
24211 ['280', '1']
24212 ['300', '1']
24213 ['310', '1']
24214 ['300', '1']
24215 ['290', '1']
24216 ['290', '1']
24217 ['300', '1']
24218 ['310', '1']
24219 ['310', '1']
24220 ['320', '1']
24221 ['310']
24222 ['310']
24223 ['310', '1']
24224 ['310']
24225 ['310', '1']
24226 ['340']
24227 ['320']
24228 ['310']
24229 ['340']
24230 ['340']
24231 ['350']
24232 ['350']
24233 ['350']
24234 ['340', '1']
24235 ['340']
24236 ['360', '1']
24237 ['360']
24238 ['360']
24239 ['350']
24240 ['330', '1']
24241 ['320', '1']
24242 ['310', '1']
24243 ['320']
24244 ['320', '1']
24245 ['310']
24246 ['330']
24247 ['330', '1']
24248 ['330']
24249 ['330']
24250 ['320']
24251 ['310']
24252 ['320']
24253 ['310']
24254 ['320']
24255 ['310']
24256 ['320']
24257 ['320']
24258 ['310']
24259 ['310']
24260 ['310']
24261 ['310']
24262 ['320']
24263 ['310']
24264 ['300']
24265 ['310']
24266 ['310']
24267 ['300']
24268 ['300']
24269 ['300']
24270 ['300']
24271 ['290']
24272 ['300']
24273 ['300']
24274 ['310']
24275 ['310']
24276 ['310']
24277 ['310']
24278 ['310']
24279 ['320']
24280 ['310']
24281 ['320']
24282 ['310']
24283 ['320']
24284 ['320']
24285 ['320']
24286 ['320']
24287 ['310']
24288 ['310']
24289 ['310']
24290 ['300']
24291 ['300']
24292 ['300']
24293 ['290']
24294 ['290']
24295 ['290']
24296 ['290']
24297 ['270']
24298 ['280']
24299 ['280']
24300 ['290']
24301 ['280']
24302 ['270']
24303 ['270']
24304 ['270']
24305 ['270']
24306 ['270']
24307 ['270']
24308 ['260']
24309 ['260']
24310 ['250']
24311 ['250']
24312 ['250']
24313 ['250']
24314 ['260']
24315 ['260']
24316 ['270']
24317 ['270']
24318 ['270']
24319 ['270']
24320 ['270']
24321 ['270']
24322 ['270']
24323 ['280']
24324 ['270']
24325 ['290']
24326 ['310']
24327 ['320']
24328 ['310']
24329 ['330']
24330 ['10']
24331 ['20']
24332 ['30']
24333 ['50']
24334 ['100']
24335 ['100']
24336 ['100']
24337 ['80']
24338 ['90']
24339 ['110']
24340 ['120']
24341 ['130']
24342 ['120']
24343 ['100']
24344 ['110']
24345 ['110']
24346 ['100']
24347 ['110']
24348 ['110']
24349 ['120']
24350 ['130']
24351 ['120']
24352 ['120']
24353 ['130']
24354 ['120']
24355 ['120']
24356 ['130']
24357 ['130']
24358 ['110']
24359 ['120']
24360 ['130']
24361 ['110']
24362 ['120']
24363 ['120']
24364 ['120']
24365 ['120']
24366 ['130']
24367 ['130']
24368 ['120']
24369 ['120']
24370 ['120']
24371 ['120']
24372 ['120']
24373 ['130']
24374 ['110']
24375 ['120']
24376 ['120']
24377 ['120']
24378 ['120']
24379 ['110']
24380 ['110']
24381 ['120']
24382 ['110']
24383 ['110']
24384 ['120']
24385 ['120']
24386 ['120']
24387 ['120']
24388 ['120']
24389 ['120']
24390 ['120']
24391 ['130']
24392 ['120']
24393 ['120']
24394 ['120']
24395 ['130']
24396 ['130']
24397 ['130']
24398 ['150']
24399 ['150']
24400 ['150']
24401 ['190']
24402 ['170']
24403 ['190']
24404 ['190']
24405 ['200']
24406 ['200']
24407 ['200']
24408 ['210']
24409 ['200']
24410 ['200']
24411 ['200']
24412 ['200']
24413 ['190']
24414 ['190']
24415 ['190']
24416 ['190']
24417 ['180']
24418 ['190']
24419 ['190']
24420 ['200']
24421 ['200']
24422 ['200']
24423 ['200']
24424 ['200']
24425 ['210']
24426 ['200']
24427 ['200']
24428 ['200']
24429 ['190']
24430 ['200']
24431 ['190']
24432 ['190']
24433 ['190']
24434 ['190']
24435 ['190']
24436 ['190']
24437 ['190']
24438 ['190']
24439 ['190']
24440 ['190']
24441 ['190']
24442 ['190']
24443 ['190']
24444 ['190']
24445 ['190']
24446 ['190']
24447 ['190']
24448 ['190']
24449 ['180']
24450 ['180']
24451 ['180']
24452 ['180']
24453 ['180']
24454 ['180']
24455 ['180']
24456 ['180']
24457 ['180']
24458 ['180']
24459 ['190', '1']
24460 ['190']
24461 ['190', '1']
24462 ['200']
24463 ['190']
24464 ['190', '1']
24465 ['190']
24466 ['190', '1']
24467 ['190', '1']
24468 ['190']
24469 ['190']
24470 ['190', '1']
24471 ['190', '1']
24472 ['200']
24473 ['200', '1']
24474 ['190', '1']
24475 ['190', '1']
24476 ['190', '1']
24477 ['190', '1']
24478 ['190', '1']
24479 ['190', '1']
24480 ['200', '1']
24481 ['200', '1']
24482 ['200', '1']
24483 ['200', '1']
24484 ['200', '1']
24485 ['200', '1']
24486 ['200']
24487 ['200']
24488 ['190', '1']
24489 ['180', '1']
24490 ['180', '1']
24491 ['170', '1']
24492 ['170', '1']
24493 ['170', '1']
24494 ['180', '1']
24495 ['180', '1']
24496 ['180', '1']
24497 ['180']
24498 ['180', '1']
24499 ['180', '1']
24500 ['180', '1']
24501 ['180', '1']
24502 ['180', '1']
24503 ['190', '1']
24504 ['190', '1']
24505 ['190', '1']
24506 ['190', '1']
24507 ['190', '1']
24508 ['190', '1']
24509 ['180', '1']
24510 ['190', '1']
24511 ['190', '1']
24512 ['190', '1']
24513 ['200', '1']
24514 ['200', '1']
24515 ['190', '1']
24516 ['200', '1']
24517 ['200', '1']
24518 ['200', '1']
24519 ['200', '1']
24520 ['200', '1']
24521 ['200', '1']
24522 ['200', '1']
24523 ['190', '1']
24524 ['200', '1']
24525 ['190', '1']
24526 ['200', '1']
24527 ['200']
24528 ['200']
24529 ['200']
24530 ['200', '1']
24531 ['190', '1']
24532 ['190', '1']
24533 ['190', '1']
24534 ['190', '1']
24535 ['190', '1']
24536 ['190', '1']
24537 ['190', '1']
24538 ['200', '1']
24539 ['200', '1']
24540 ['200', '1']
24541 ['200', '1']
24542 ['200', '1']
24543 ['200', '1']
24544 ['200', '1']
24545 ['200', '1']
24546 ['210', '1']
24547 ['210']
24548 ['210', '1']
24549 ['210', '1']
24550 ['210']
24551 ['40']
24552 ['40']
24553 ['10']
24554 ['30']
24555 ['40']
24556 ['30']
24557 ['360']
24558 ['30']
24559 ['40']
24560 ['330']
24561 ['10']
24562 ['100']
24563 ['90']
24564 ['100']
24565 ['100']
24566 ['120']
24567 ['130', '1']
24568 ['130', '1']
24569 ['130', '1']
24570 ['130', '1']
24571 ['140', '1']
24572 ['140']
24573 ['140']
24574 ['140']
24575 ['140']
24576 ['140']
24577 ['150']
24578 ['150']
24579 ['160']
24580 ['210']
24581 ['210']
24582 ['200']
24583 ['200']
24584 ['190', '1']
24585 ['190', '1']
24586 ['200', '1']
24587 ['200', '1']
24588 ['200', '1']
24589 ['200', '1']
24590 ['210']
24591 ['210']
24592 ['210']
24593 ['220']
24594 ['240']
24595 ['230']
24596 ['220']
24597 ['230', '1']
24598 ['210']
24599 ['210']
24600 ['210']
24601 ['220', '1']
24602 ['220', '1']
24603 ['220']
24604 ['220']
24605 ['220']
24606 ['230']
24607 ['220']
24608 ['240', '1']
24609 ['240']
24610 ['240', '1']
24611 ['240']
24612 ['230']
24613 ['250']
24614 ['230']
24615 ['240']
24616 ['230']
24617 ['240']
24618 ['240']
24619 ['240']
24620 ['230']
24621 ['240']
24622 ['220']
24623 ['230']
24624 ['230']
24625 ['230']
24626 ['220']
24627 ['230']
24628 ['220']
24629 ['230']
24630 ['230']
24631 ['220']
24632 ['220', '1']
24633 ['220', '1']
24634 ['210']
24635 ['220', '1']
24636 ['240']
24637 ['230']
24638 ['240']
24639 ['230']
24640 ['220', '1']
24641 ['240']
24642 ['240']
24643 ['230']
24644 ['240']
24645 ['240']
24646 ['220']
24647 ['230', '1']
24648 ['240', '1']
24649 ['230', '1']
24650 ['230', '1']
24651 ['230', '1']
24652 ['240']
24653 ['220']
24654 ['220']
24655 ['240']
24656 ['240']
24657 ['250']
24658 ['220']
24659 ['230']
24660 ['220']
24661 ['210', '1']
24662 ['220']
24663 ['220']
24664 ['230']
24665 ['240']
24666 ['230']
24667 ['220']
24668 ['220']
24669 ['230']
24670 ['240']
24671 ['260']
24672 ['240']
24673 ['240']
24674 ['240']
24675 ['240']
24676 ['300']
24677 ['280', '1']
24678 ['270']
24679 ['300']
24680 ['290']
24681 ['290']
24682 ['270']
24683 ['210']
24684 ['160']
24685 ['160']
24686 ['150']
24687 ['170']
24688 ['180']
24689 ['170']
24690 ['180']
24691 ['180']
24692 ['240']
24693 ['180']
24694 ['200']
24695 ['210']
24696 ['190']
24697 ['200']
24698 ['190']
24699 ['190']
24700 ['200']
24701 ['210']
24702 ['240']
24703 ['210']
24704 ['230']
24705 ['240']
24706 ['230']
24707 ['250']
24708 ['250']
24709 ['260']
24710 ['250']
24711 ['260']
24712 ['260']
24713 ['250']
24714 ['250']
24715 ['250']
24716 ['240']
24717 ['170']
24718 ['200']
24719 ['200']
24720 ['200']
24721 ['200']
24722 ['200']
24723 ['200']

24724 ['190']
24725 ['190']
24726 ['190']
24727 ['200']
24728 ['200']
24729 ['200']
24730 ['190']
24731 ['180']
24732 ['180']
24733 ['200']
24734 ['200']
24735 ['200']
24736 ['200']
24737 ['200']
24738 ['200']
24739 ['210']
24740 ['200']
24741 ['210']
24742 ['210']
24743 ['210']
24744 ['210']
24745 ['210']
24746 ['210']
24747 ['210']
24748 ['200']
24749 ['200']
24750 ['200']
24751 ['200']
24752 ['200']
24753 ['190']
24754 ['200']
24755 ['210']
24756 ['10']
24757 ['340']
24758 ['330']
24759 ['330']
24760 ['10']
24761 ['30']
24762 ['40']
24763 ['50']
24764 ['50']
24765 ['50']
24766 ['50']
24767 ['60']
24768 ['70']
24769 ['60']
24770 ['50']
24771 ['70']
24772 ['70']
24773 ['80']
24774 ['70']
24775 ['80']
24776 ['90']
24777 ['80']
24778 ['60']
24779 ['80']
24780 ['50']
24781 ['40']
24782 ['90']
24783 ['90']
24784 ['80']
24785 ['90']
24786 ['90']
24787 ['90']
24788 ['90']
24789 ['90']
24790 ['100']
24791 ['140']
24792 ['150']
24793 ['170']
24794 ['170']
24795 ['180']
24796 ['170']
24797 ['170']
24798 ['170']
24799 ['160']
24800 ['170']
24801 ['170']
24802 ['150']
24803 ['160']
24804 ['160']
24805 ['150']
24806 ['160']
24807 ['160']
24808 ['170']
24809 ['180']
24810 ['190']
24811 ['190']
24812 ['180']
24813 ['190']
24814 ['180']
24815 ['170']
24816 ['180']
24817 ['170']
24818 ['180']
24819 ['180']
24820 ['180']
24821 ['190']
24822 ['180']
24823 ['180']
24824 ['180']
24825 ['190']
24826 ['190']
24827 ['200']
24828 ['200']
24829 ['200']
24830 ['210']
24831 ['220']
24832 ['260']
24833 ['270']
24834 ['340']
24835 ['10']
24836 ['30']
24837 ['40']
24838 ['40']
24839 ['30']
24840 ['280']
24841 ['290']
24842 ['250']
24843 ['260']
24844 ['300']
24845 ['280']
24846 ['240']
24847 ['250']
24848 ['240']
24849 ['260']
24850 ['260']
24851 ['270']
24852 ['270']
24853 ['270']
24854 ['270']
24855 ['280']
24856 ['280']
24857 ['280']
24858 ['280']
24859 ['280']
24860 ['280']
24861 ['280']
24862 ['270']
24863 ['270']
24864 ['270']
24865 ['280']
24866 ['270']
24867 ['270']
24868 ['270']
24869 ['270']
24870 ['270']
24871 ['280']
24872 ['280']
24873 ['280']
24874 ['290']
24875 ['280']
24876 ['270']
24877 ['270']
24878 ['270']
24879 ['270']
24880 ['270']
24881 ['270']
24882 ['270']
24883 ['270']
24884 ['270']
24885 ['270']
24886 ['270']
24887 ['270']
24888 ['250']
24889 ['250']
24890 ['240']
24891 ['260']
24892 ['260']
24893 ['260']
24894 ['300']
24895 ['300']
24896 ['300']
24897 ['310']
24898 ['310']
24899 ['320']
24900 ['320']
24901 ['350']
24902 ['360']
24903 ['20']
24904 ['360']
24905 ['50']
24906 ['30']
24907 ['40']
24908 ['50']
24909 ['40']
24910 ['50']
24911 ['70']
24912 ['140']
24913 ['100']
24914 ['100']
24915 ['100']
24916 ['90']
24917 ['110']
24918 ['100']
24919 ['110']
24920 ['100']
24921 ['130']
24922 ['120']
24923 ['120']
24924 ['120']
24925 ['110']
24926 ['120']
24927 ['120']
24928 ['110']
24929 ['140']
24930 ['130']
24931 ['130']
24932 ['130']
24933 ['200']
24934 ['270']
24935 ['250']
24936 ['260']
24937 ['280', '1']
24938 ['270']
24939 ['280']
24940 ['280']
24941 ['280']
24942 ['270']
24943 ['280']
24944 ['280']
24945 ['270']
24946 ['270']
24947 ['280', '1']
24948 ['290']
24949 ['300', '1']
24950 ['290']
24951 ['290']
24952 ['270']
24953 ['290', '1']
24954 ['280']
24955 ['280']
24956 ['280']
24957 ['280']
24958 ['280']
24959 ['280']
24960 ['280']
24961 ['290']
24962 ['290']
24963 ['290']
24964 ['280']
24965 ['280']
24966 ['280']
24967 ['280']
24968 ['280']
24969 ['270']
24970 ['270']
24971 ['280']
24972 ['280']
24973 ['290']
24974 ['280']
24975 ['280']
24976 ['280']
24977 ['280']
24978 ['280']
24979 ['280']
24980 ['290']
24981 ['290']
24982 ['300']
24983 ['300']
24984 ['300']
24985 ['300']
24986 ['300']
24987 ['300']
24988 ['290']
24989 ['290']
24990 ['290']
24991 ['280']
24992 ['280']
24993 ['280']
24994 ['290']
24995 ['280']
24996 ['280']
24997 ['280']
24998 ['290']
24999 ['290']

In [89]:
series = data_2017['WDIR']

In [92]:
# data = []
# j = 0 
# for i in range(len(data_2017['WDIR'])):
#     if i % 1000 == 0:
#         j += i
#         print(f'Checking item {i}')
    
#     if len(series.loc[i].split()) == 1:
#         pass
#     else:
#         data0 = series.loc[i]
#         data1 = data0.split()
#         series.loc[i] = data1[0]

Checking item 0
Checking item 1000

/Users/blakewallace/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:190: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
/Users/blakewallace/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]

Checking item 2000
Checking item 3000
Checking item 4000
Checking item 5000
Checking item 6000
Checking item 7000
Checking item 8000
Checking item 9000
Checking item 10000
Checking item 11000
Checking item 12000
Checking item 13000
Checking item 14000
Checking item 15000
Checking item 16000
Checking item 17000
Checking item 18000
Checking item 19000
Checking item 20000
Checking item 21000
Checking item 22000
Checking item 23000
Checking item 24000
Checking item 25000
Checking item 26000
Checking item 27000
Checking item 28000
Checking item 29000
Checking item 30000
Checking item 31000
Checking item 32000
Checking item 33000
Checking item 34000
Checking item 35000
Checking item 36000
Checking item 37000
Checking item 38000
Checking item 39000
Checking item 40000
Checking item 41000
Checking item 42000
Checking item 43000
Checking item 44000
Checking item 45000
Checking item 46000
Checking item 47000
Checking item 48000
Checking item 49000
Checking item 50000

In [94]:
data_2017['WDIR'] = series
data_2017['WDIR'].head()

/Users/blakewallace/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

0    280
1    280
2    280
3    280
4    280
Name: WDIR, dtype: object

In [95]:
for i in range(len(data_2017['WDIR'])):
    if len(data_2017['WDIR'].loc[i].split()) == 1:
        pass
    else:
        print(i, data_2017['WDIR'].loc[i].split())
print('Everything checks out.')

Everything checks out.

In [97]:
data_2017['WDIR'] = data_2017['WDIR'].astype('int')

/Users/blakewallace/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [151]:
# saving the 2017 chii2 buoy data to a csv.
data_2017.to_csv('../data/buoy_CHII2/chii2_buoy_data_2017.csv')

In [152]:
# print(len(data_2017.groupby(['#YY', 'MM', 'DD']).mean().drop(['hh', 'mm'], axis=1)))
data_2017.groupby(['#YY', 'MM', 'DD']).mean().drop(['hh', 'mm'], axis=1).head()

                  WDIR      WSPD        GST       ATMP       DEWP
#YY  MM DD
2017 1  1   224.444444  5.077083   5.627083  -0.279861  -5.688889
        2   107.569444  5.112500   5.362500   3.128472   0.209028
        3   214.513889  4.586111   5.272222   3.626389   3.413194
        4   281.527778  2.915278  12.878472  -6.640972 -11.584028
        5   279.366197  6.039437  10.133803 -11.634507 -17.369718

In [153]:
# checking to see which months are missing days
for i in range(1, 13):
    print(i, len(data_2017[data_2017['MM'] == i]['DD'].value_counts()))

1 31
2 28
3 31
4 30
5 31
6 30
7 31
8 31
9 30
10 31
11 30
12 30

<a id='Dec25,2017'></a>

In [101]:
# missing data, Dec. 25, 2017
data_2017.groupby(['#YY', 'MM', 'DD']).mean().drop(['hh', 'mm'], axis=1).tail(10)

                  WDIR      WSPD        GST       ATMP        DEWP
#YY  MM DD
2017 12 21  109.444444  5.759722   7.068056   2.261806   -3.025694
        22  204.929577  4.599296   5.015493   3.185211   -0.066901
        23  334.305556  7.000694   7.984722  -0.156250   -4.715278
        24  247.387387  5.000901   5.863964  -3.881081   -8.551351
        26  270.277778  7.566667   8.941667 -14.719444  999.000000
        27  297.535211  7.492254   8.773944 -15.364789  999.000000
        28  242.361111  5.629167   6.679167 -12.113194  618.443056
        29  262.361111  6.245833   7.381250 -10.185417  -13.697222
        30  293.194444  5.498611  10.222222 -11.781944  -16.509722
        31  301.830986  7.321127   8.495775 -13.881690  -18.978169

<a id='2018'></a>
### Exploring the data for 2018.

#### Missing data

[Dec. 27-31, 2018](#Dec27-31,2018)

In [102]:
data_18 = pd.read_csv('../data/buoy_CHII2/chii2h2018.csv')
print(data_18.shape)
data_18.head()

(50269, 18)

,#YY,MM,DD,hh,mm,WDIR,WSPD,GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,TIDE
0,2018,1,1,0,0,300,9.3,10.8,99,99,99,999,9999,-11.2,999,-18.6,99,99
1,2018,1,1,0,10,310,8.8,9.8,99,99,99,999,9999,-11.5,999,-18.6,99,99
2,2018,1,1,0,20,300,9.8,10.3,99,99,99,999,9999,-11.6,999,-18.5,99,99
3,2018,1,1,0,30,310,9.3,10.8,99,99,99,999,9999,-11.9,999,-18.8,99,99
4,2018,1,1,0,40,300,9.8,11.3,99,99,99,999,9999,-12.1,999,-18.4,99,99

In [103]:
data_18.dtypes

#YY       int64
MM        int64
DD        int64
hh        int64
mm        int64
WDIR      int64
WSPD    float64
GST     float64
WVHT      int64
DPD       int64
APD       int64
MWD       int64
PRES      int64
ATMP    float64
WTMP      int64
DEWP    float64
VIS       int64
TIDE      int64
dtype: object

In [104]:
data_2018 = data_18[features]
print(data_2018.shape)
data_2018.head()

(50269, 10)

    #YY  MM  DD  hh  mm  WDIR  WSPD   GST  ATMP  DEWP
0  2018   1   1   0   0   300   9.3  10.8 -11.2 -18.6
1  2018   1   1   0  10   310   8.8   9.8 -11.5 -18.6
2  2018   1   1   0  20   300   9.8  10.3 -11.6 -18.5
3  2018   1   1   0  30   310   9.3  10.8 -11.9 -18.8
4  2018   1   1   0  40   300   9.8  11.3 -12.1 -18.4

In [105]:
print(len(data_2018.groupby(['#YY', 'MM', 'DD']).mean().drop(['hh', 'mm'], axis=1)))
data_2018.groupby(['#YY', 'MM', 'DD']).mean().drop(['hh', 'mm'], axis=1).head()

360

                  WDIR       WSPD        GST       ATMP       DEWP
#YY  MM DD
2018 1  1   291.785714   8.993571  10.382143 -16.937857 -22.438571
        2   257.000000   7.611429   8.913571 -16.668571 -21.556429
        3   256.319444  10.136111  11.827083 -10.247917 -15.077083
        4   316.808511   8.172340   9.485106 -11.898582 -16.797872
        5   313.194444   8.295139   9.545139 -13.047222 -18.440972

In [106]:
for i in range(1, 13):
    print(i, len(data_2018[data_2018['MM'] == i]['DD'].value_counts()))

1 31
2 28
3 31
4 30
5 31
6 30
7 31
8 31
9 30
10 31
11 30
12 26

<a id='Dec27-31,2018'></a>

In [107]:
# missing data, Dec. 27-31, 2018
data_2018.groupby(['#YY', 'MM', 'DD']).mean().drop(['hh', 'mm'], axis=1).tail()

                  WDIR      WSPD       GST      ATMP      DEWP
#YY  MM DD
2018 12 22  260.352113  5.314789  6.111972 -0.233099 -3.452817
        23  249.084507  5.961972  6.719718  1.383099 -2.318310
        24  252.708333  7.311111  8.481250 -0.649306 -7.449306
        25  196.736111  4.321528  4.950000  2.933333 -1.990972
        26  154.117647  1.503529  1.694118  3.534118  1.800000

<a id='2019'></a>
### Exploring the data for 2019.

In [108]:
# data_19 = pd.read_csv('../data/buoy_CHII2/chii2h2019.csv')

### Combining all of the dataframes from 2015 - 2018 into one giant dataframe.

### Table of contents

Exploring the data:  
[2005](#2005), 
[2006](#2006), 
[2007](#2007),  
[2008](#2008)  
[2009](#2009)  
[2010](#2010)  
[2011](#2011)  
[2012](#2012)  
[2013](#2013)  
[2014](#2014), 
[2015](#2015),
[2016](#2016), 
[2017](#2017), 
[2018](#2018), 
[2019](#2019)  

#### Missing data
 - [Dec 5-13, 2015](#Dec5-13,2015)
 - [Nov. 30, 2016](#Nov30,2016)
 - [Dec 25, 2017](#Dec25,2017)
 - [Dec. 27-31, 2018](#Dec27-31,2018)

In [4]:
data = pd.concat([data_2015, data_2016, data_2017, data_2018], axis=0)
print(data.shape)
data.head()

NameError: name 'data_2015' is not defined

In [183]:
print(data.groupby(['#YY', 'MM', 'DD']).mean().drop(['hh', 'mm'], axis=1).shape)
data.groupby(['#YY', 'MM', 'DD']).mean().drop(['hh', 'mm'], axis=1).head()

(1444, 5)

                  WDIR       WSPD        GST       ATMP   DEWP
#YY  MM DD
2015 1  1   232.083333  10.191667  14.289583  -6.083333  999.0
        2   220.000000   5.331250   6.541667  -2.022917  999.0
        3   168.229167   4.597917   5.357292   0.307292  999.0
        4   314.062500   7.702083   9.019792  -1.535417  999.0
        5   270.625000   9.589583  12.181250 -15.468750  999.0

In [184]:
data.dtypes

#YY       int64
MM        int64
DD        int64
hh        int64
mm        int64
WDIR      int64
WSPD    float64
GST     float64
ATMP    float64
DEWP    float64
dtype: object

In [10]:
data = pd.read_csv('../data/buoy_CHII2/chii2_buoy_data_2015_2018.csv')

In [11]:
data.to_csv('../data/buoy_CHII2/chii2_buoy_data_2015_2018.csv', index=False)

In [12]:
data = pd.read_csv('../data/buoy_CHII2/chii2_buoy_data_2015_2018.csv')
print(data.shape)
data.head()

(186896, 12)

,Unnamed: 0,Unnamed: 0.1,#YY,MM,DD,hh,mm,WDIR,WSPD,GST,ATMP,DEWP
0,0,0,2015,1,1,0,0,220,10.8,13.9,-7.2,999.0
1,1,1,2015,1,1,0,15,220,11.8,15.4,-7.2,999.0
2,2,2,2015,1,1,0,30,220,11.8,17.0,-7.1,999.0
3,3,3,2015,1,1,0,45,220,12.4,17.0,-6.9,999.0
4,4,4,2015,1,1,1,0,220,12.9,19.0,-7.0,999.0

In [14]:
data = data.drop(['Unnamed: 0', 'Unnamed: 0.1'], axis=1)

In [15]:
data.to_csv('../data/buoy_CHII2/chii2_buoy_data_2015_2018.csv', index=False)

In [16]:
data = pd.read_csv('../data/buoy_CHII2/chii2_buoy_data_2015_2018.csv')
print(data.shape)
data.head()

(186896, 10)

    #YY  MM  DD  hh  mm  WDIR  WSPD   GST  ATMP   DEWP
0  2015   1   1   0   0   220  10.8  13.9  -7.2  999.0
1  2015   1   1   0  15   220  11.8  15.4  -7.2  999.0
2  2015   1   1   0  30   220  11.8  17.0  -7.1  999.0
3  2015   1   1   0  45   220  12.4  17.0  -6.9  999.0
4  2015   1   1   1   0   220  12.9  19.0  -7.0  999.0

In [24]:
grouped_data = data.groupby(['#YY', 'MM', 'DD']).mean().drop(['hh', 'mm', 'DEWP'], axis=1)

In [26]:
print(grouped_data.shape)
grouped_data.head()

(1444, 4)

                  WDIR       WSPD        GST       ATMP
#YY  MM DD
2015 1  1   232.083333  10.191667  14.289583  -6.083333
        2   220.000000   5.331250   6.541667  -2.022917
        3   168.229167   4.597917   5.357292   0.307292
        4   314.062500   7.702083   9.019792  -1.535417
        5   270.625000   9.589583  12.181250 -15.468750