# Analysis of the data for January 2015 - December 2018

## Data Sources
#### [CHICAGO OHARE INTERNATIONAL AIRPORT, IL US](https://www.ncdc.noaa.gov/cdo-web/results)
 - Source: [National Centers for Environmental Information](https://www.ncdc.noaa.gov/cdo-web/search)  
 - [GHCN (Global Historical Climatology Network) – Daily Documentation](https://www1.ncdc.noaa.gov/pub/data/cdo/documentation/GHCND_documentation.pdf)
  - ID	GHCND:USW00094846  
    41.995 N 87.9336 W 

#### [Station FSTI2 - Foster Ave., Chicago, IL](https://www.ndbc.noaa.gov/station_page.php?station=fsti2)
 - Source: [National Data Buoy Center](https://www.ndbc.noaa.gov/)

 - Owned and maintained by [Chicago Park District](https://www.ndbc.noaa.gov/ndbcexit.php?url=https://wqdatalive.com/public/16&blurb=Chicago+Park+District)  
    41.976 N 87.648 W (41°58'35" N 87°38'51" W)
    
#### [Lake Michigan](https://www.google.com/search?q=lake+michigan&oq=lake+michigan&aqs=chrome.0.69i59j69i60l3j69i59j0.3015j0j9&sourceid=chrome&ie=UTF-8)
 - Source: [Great Lakes Statistics: Average Surface Water Temperature from the Great Lakes Surface Environmental Analysis (GLSEA)](https://coastwatch.glerl.noaa.gov/statistic/statistic.html)
 - 44.0 -87.0 (44° 00' 0.00" N 87° 00' 0.00" W)
 - [Data Set for 2018](https://coastwatch.glerl.noaa.gov/ftp/glsea/avgtemps/2018/glsea-temps2018_1024.dat)

#### Data Dictionary

 - **lake_temp (Celsius)** - Average Daily Surface Water Temperature for Lake Michigan 
 - **buoy_wdir (degT)** - Wind direction (the direction the wind is coming from in degrees clockwise from true N) during the same period used for WSPD. (WDIR) 
 - **buoy_wspd (m/s)** - Wind speed averaged over an eight-minute period for buoys and a two-minute period for land stations. Reported Hourly.
 - **buoy_atmp (Celsius)** - Air temperature
 - **ohare_wspd** - Average Wind Speed (AWND) () 
 - **ohare_prcp** - Precipitation (PRCP)/ Total Daily amount ()
 - **ohare_snfall** - Snowfall (SNOW)/ Total Daily amount ()
 - **ohare_sndpth** - Snow depth (SNWD)/ Amount of snow on the ground () 
 - **ohare_atmp** - Average Temperature (TAVG) ()
 - **ohare_maxtmp** - Maximum Temperature (TMAX) ()
 - **ohare_mintmp** - Minimum Temperature (TMIN) ()
 
 [Bouy Data Dictionary](https://www.ndbc.noaa.gov/measdes.shtml)  
 [O'Hare Airport Data Dictionary]()

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn

import time

%matplotlib inline

In [2]:
df = pd.read_csv('data/merged/jan012015_dec312018.csv')
print(df.shape)
df.head()

(1461, 12)

,DATE,lake_temp,buoy_wdir,buoy_wspd,buoy_atmp,ohare_wspd,ohare_prcp,ohare_snfall,ohare_sndpth,ohare_atmp,ohare_maxtmp,ohare_mintmp
0,2015-01-01,3.53,238.333333,9.890476,-5.928571,14.54,0.00,0.0,0.0,20.0,32,14
1,2015-01-02,3.50,216.086957,6.230435,-2.204348,4.70,0.00,0.0,0.0,26.0,34,15
2,2015-01-03,3.49,181.916667,5.654167,0.395833,5.59,0.57,0.4,0.0,31.0,34,29
3,2015-01-04,3.36,313.750000,8.779167,-1.545833,15.88,0.13,2.2,1.2,29.0,33,2
4,2015-01-05,3.16,262.166667,9.537500,-16.145833,10.29,0.15,1.8,2.0,2.0,6,-3